### ISSUE TITLE
Programatically go to next

### ISSUE THREAD

**Issue by jangerhard** [stepstone-tech/android-material-stepper#100]
Great library! 

I'm currently developing an application where the user goes to a fragment where he/she is greeted with a countdown, and once the countdown and background actions have taken place, I want the next-button to automatically be clicked without having the user click it. 

Is there a way of doing this? I might be missing something.

**Comment by zawadz88** [comment]
Hi @jangerhard,
You can go programatically to the next step. Please see #68 and the sample app https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/ProceedProgrammaticallyActivity.java

**Comment by jangerhard** [comment]
Am I missing anything? It seems like the sample is an activity, which does not help me go programatically to the next step. Can I reference mStepperLayout in an easy way?

**Comment by zawadz88** [comment]
Hi @jangerhard,
StepperLayout has methods for going to next/previous steps which are in the linked Activity i.e. `StepperLayout#proceed()` and `StepperLayout#onBackClicked()`. There's also `StepperLayout#setCurrentStepPosition(int)`. 

The linked Activity is a starting point, see the related Fragment as well (https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/step/fragment/FormStepFragment.java). Please see the sample app for more details.

**Comment by jangerhard** [comment]
Hi @zawadz88,

Thanks for the quick response. I've implemented the OnProceedListener, so that the fragment can call the onProceed method in the main activity, but I keep getting this error message. 

`java.lang.IllegalStateException: Must be called from main thread of fragment host`

I've checked, and my code is pretty much identical to the samples you've provided, so I'm not sure where the problem is. 

Fragment: 

```
@Nullable
    private OnProceedListener onProceedListener;
 @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnProceedListener) {
            onProceedListener = (OnProceedListener) context;
        }
    }

// Called when countdown is finished
 private void goToNext() {
        if (onProceedListener != null) {
            onProceedListener.onProceed();
        }
    }
```

Activity: 

```
public class StepperActivity extends AppCompatActivity implements StepperLayout.StepperListener, OnProceedListener {

private String TAG = "Main";

    public StepperLayout mStepperLayout;
    private static final String CURRENT_STEP_POSITION_KEY = "position";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mStepperLayout = (StepperLayout) findViewById(R.id.stepperLayout);
        int startingStepPosition = savedInstanceState != null ? savedInstanceState.getInt(CURRENT_STEP_POSITION_KEY) : 0;
        mStepperLayout.setAdapter(new MyStepperAdapter(getSupportFragmentManager(), this), startingStepPosition);
        mStepperLayout.setListener(this);
    }

 @Override
    public void onProceed() {
        Log.i(TAG, "On proceed called in StepperActivity");
        mStepperLayout.proceed();
    }

... 

}

**Comment by jangerhard** [comment]
EDIT: 

I've checked the logs, and I've found that mStepperLayout will actually correctly click the next button, but the problem is when `StepperLayout.onUpdate` is called. 

The full error message 

> FATAL EXCEPTION: Thread-4618
>                                                                      Process: seecode.nomo.nomo3d, PID: 11638
>                                                                      java.lang.IllegalStateException: Must be called from main thread of fragment host
>                                                                          at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1960)
>                                                                          at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1975)
>                                                                          at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
>                                                                          at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
>                                                                          at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
>                                                                          at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668)
>                                                                          at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
>                                                                          at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:611)
>                                                                          at com.stepstone.stepper.StepperLayout.onUpdate(StepperLayout.java:636)
>                                                                          at com.stepstone.stepper.StepperLayout.access$200(StepperLayout.java:65)
>                                                                          at com.stepstone.stepper.StepperLayout$OnNextClickedCallback.goToNextStep(StepperLayout.java:131)
>                                                                          at seecode.nomo.nomo3d.fragments.StanceFragment.onNextClicked(StanceFragment.java:220)
>                                                                          at com.stepstone.stepper.StepperLayout.onNext(StepperLayout.java:598)
>                                                                          at com.stepstone.stepper.StepperLayout.proceed(StepperLayout.java:338)
>                                                                          at seecode.nomo.nomo3d.StepperActivity$override.onProceed(StepperActivity.java:76)
>                                                                          at seecode.nomo.nomo3d.StepperActivity$override.access$dispatch(StepperActivity.java)
>                                                                          at seecode.nomo.nomo3d.StepperActivity.onProceed(StepperActivity.java:0)
>                                                                          at seecode.nomo.nomo3d.fragments.StanceFragment.goToNext(StanceFragment.java:170)
>                                                                          at seecode.nomo.nomo3d.fragments.StanceFragment.access$400(StanceFragment.java:30)
>                                                                          at seecode.nomo.nomo3d.fragments.StanceFragment$2.run(StanceFragment.java:155)
>                                                                          at java.lang.Thread.run(Thread.java:818)
> 
>

**Comment by zawadz88** [comment]
It looks like you're trying to do this on a background thread, this must be done on the main thread

**Comment by jangerhard** [comment]
Thanks! Yeah, I had the call inside a Thread, and that was causing the entire issue. I'll try to refactor my code with this in mind. Thank you!

**Comment by lucasharada** [comment]
@jangerhard Hey! Can you give some insight on how I can make it work too? I have the same need you had. I'll try to list the steps I got from this issue:

1. Implement a Interface class (named OnProceedListener)
2. Make the main Activity that holds the Stepper implement the created Interface
3. Instanciate the Interface in the Fragment and call the onProceed() method so the StepperLayout object can go to the next step.

**Comment by jangerhard** [comment]
@lucasharada 

Hey! It seems like you're pretty much correct in all steps. Under is how I did it. 

1. Implement a Interface class (named OnProceedListener) with a method called 

```
public interface OnProceedListener{

    void onProceed();
}
```

2. Make the main Activity that holds the Stepper implement the created Interface and call method.

```
public class StepperActivity extends AppCompatActivity implements StepperLayout.StepperListener, OnProceedListener {

public StepperLayout mStepperLayout;

 ...

@Override
public void onProceed() {
  mStepperLayout.proceed();
}

}
```

3. in the Fragment,  and call the onProceed() method so the StepperLayout object can go to the next step.

```
public class fragment extends Fragment implements BlockingStep {

    @Nullable
    private OnProceedListener onProceedListener;

    --
     // Needs to go to next here
     if (onMainListener != null)
         onMainListener.onProceed();

    --

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnMainListener) {
            onMainListener = (OnMainListener) context;
        }
    }
}
```


I really hope that helps! Let me know if you have any more issues.
