### ISSUE TITLE
Color of tabs

### ISSUE THREAD

**Issue by tonno16** [stepstone-tech/android-material-stepper#101]
I used tabs mode for layout. I am able to change all color of widget, but I cannot change background color of tab indicator.

**Comment by fabiozo** [comment]
Hi @tonno16 

You can change color of selected tab by customising ms_activeStepColor attribute in your layout.

e.g. app:ms_activeStepColor="#FFFFFF"

Let us know it this is what you need.

Thanks

**Comment by multivoltage** [comment]
I try:
`        app:ms_activeStepColor="@color/colorPrimary"
        app:ms_nextButtonColor="@color/colorPrimary"
        app:ms_backButtonColor="@color/colorPrimary"
        app:ms_completeButtonColor="@color/colorPrimary"
        app:ms_errorColor="@color/colorAccent"`

I want to change the default white background of layout in the tabs

**Comment by zawadz88** [comment]
Hi @tonno16 @multivoltage,
Please see https://github.com/stepstone-tech/android-material-stepper#custom-styling and 'Custom StepperLayout theme' example in the sample app. You can style almost any internal view of the StepperLayout by using `ms_stepperLayoutTheme` attribute with your custom style.
E.g. to change the background color of the tab container you need to:

1. Use `ms_stepperLayoutTheme` attribute on your view in XML with a reference to a custom style:

```
<com.stepstone.stepper.StepperLayout 
        android:id="@+id/stepperLayout"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:ms_stepperLayoutTheme="@style/CustomStepperLayoutTheme"/>
```

2. Define the style in XML, e.g. `styles.xml`:

```
    <style name="CustomStepperLayoutTheme" parent="MSDefaultStepperLayoutTheme">
        <item name="ms_tabsContainerStyle">@style/CustomStepTabsContainerStyle</item>
    </style>

    <style name="CustomStepTabsContainerStyle" parent="MSStepTabsContainer">
        <item name="android:background">@color/myTabBackgroundColor</item>
    </style>

```

Please let us know if this works for you.

**Comment by multivoltage** [comment]
Thanks so much
