### ISSUE TITLE
Programmatically call the next step button

### ISSUE THREAD

**Issue by christianlacerda** [stepstone-tech/android-material-stepper#103]
Hi, Guys!

Excellent job with the library! 
I was just wondering if is there any way to trigger the next step cycle programmatically. I have a list in one of my steps and I'd like the user to go to the next step as soon as s/he clicks on one of the list items (i.e. not clicking on the next step button).

**Comment by christianlacerda** [comment]
Nevermind, I just noticed the method `stepperLayout.proceed()`

Thanks!

**Comment by vzool** [comment]
Hi @christianlacerda,

How can I access `stepperLayout.proceed()` from `Fragment`?

Thanks

**Comment by christianlacerda** [comment]
Hi @vzool,

You should have your activity implementing an interface in order to get the stepperLayout reference, something similar to: `(getActivity()(HasStepperLayout)).stepperLayout().proceed()`

Hope, it helps!

**Comment by vzool** [comment]
Aha, nice!

I put the full snippet here which explains as a reference for anyone will need this:

```java
// The Activity

public class FormActivity extends Activity implements StepperLayout.StepperListener{
    
      // Make it `public` to easy access and avoid using `static`
      // Because it could lead to Memory Leak and unpredicted crashes

      public StepperLayout mStepperLayout;

      // ...
}

// The Fragment

public class FragmentA extends Fragment implements Step {

   FragmentA(){

      // Access StepperLayout by casting through `getActivity()` 

      ((FormActivity)getActivity()).mStepperLayout.setCurrentStepPosition(0);
   }

   // ..
}
```
Thanks for your help

**Comment by Rainer-Lang** [comment]
Look here: https://github.com/stepstone-tech/android-material-stepper/issues/100
