### ISSUE TITLE
Hide "COMPLETE" button from navigation

### ISSUE THREAD

**Issue by stedi-akk** [stepstone-tech/android-material-stepper#104]
It would be great to have possibility to hide this button

**Comment by Ilan321** [comment]
Isn't it already implemented? It's `StepperLayout.setCompleteButtonEnabled(bool enabled)`

**Comment by stedi-akk** [comment]
This method disables button click function, and nothing more.

**Comment by Ilan321** [comment]
Try removing the text and image in the builder

**Comment by stedi-akk** [comment]
Well, hacks I always can do. But I prefer normal code in my own apps :)

**Comment by zawadz88** [comment]
Hi @stedi-akk,
Could you provide a use case where this could be useful? Removing the complete button seems like a custom thing and I'm not sure whether it should be a part of this library TBH.
Thanks

**Comment by Ilan321** [comment]
Having one of those "first run" introduction steppers and then on the last
step having the user log in?

**Comment by stedi-akk** [comment]
I have my own "finish" button on the last "conclusion" step. That button is big, and centered in layout. Generally, my button is more visible to user, than this small "CONTINUE" button.

**Comment by zawadz88** [comment]
Thanks for your feedback. I'm wondering whether this shouldn't be on per step basis, i.e. showing Next/Complete could be configured on the adapter level with the default being to show the buttons. What are your thoughts?

**Comment by Ilan321** [comment]
Yeah, implementing this on a per-step basis would be better than just the
final step. For example, you could ask the user to log in at the first step
and then show the "tour" afterwards.

**Comment by stedi-akk** [comment]
I think StepperLayout.setCompleteButtonVisible(bool visible) would be enough, because this button shows only once (on the last step). "Next" / "Back" buttons are okay, and I think that they should always be visible.

**Comment by zawadz88** [comment]
I'm leaning more towards what @Ilan321 is saying.
From my perspective, it would be better to handle both buttons as new functionality requests were historically usually raised for both buttons in the Issues.

I'll gladly review any PRs regarding this :)

**Comment by zawadz88** [comment]
Merged to `develop`. This will be in the next release.
Thanks for contributing!
