### ISSUE TITLE
How to add / remove fragment from adapter ? 

### ISSUE THREAD

**Issue by beraybentesen** [stepstone-tech/android-material-stepper#110]
Example sets fragment in adapter and adds same fragment as given count. This is not the best approach for stepper view. I tried to use list and return each fragment but it is also not possible since default Fragment does not implement Stepper interface.

**Comment by zawadz88** [comment]
Hi @beraybentesen,
Could you reference the example you mentioned and provide more details?
I don't understand the issue you're having TBH.

**Comment by zawadz88** [comment]
Hi @beraybentesen,
Could you provide more details, please?
