### ISSUE TITLE
Anko DSL error

### ISSUE THREAD

**Issue by pauliusrum** [stepstone-tech/android-material-stepper#112]
When using [anko DSL](https://github.com/Kotlin/anko) the stepper view crashes when inflating the xml.

Error: `android.view.InflateException: Binary XML file line #10: Error inflating class com.stepstone.stepper.internal.widget.TabsContainer`

How to reproduce:
1. Write an extension for the stepper layout
```kotlin
inline fun ViewManager.stepperLayout(theme: Int = 0) = stepperLayout(theme) {}
inline fun ViewManager.stepperLayout(theme: Int = 0, init: StepperLayout.() -> Unit) = ankoView({ StepperLayout(it) }, theme, init)
```
2. In your activity add the DSL code
```kotlin
verticalLayout {
    stepperLayout {  }
}
```

**Comment by zawadz88** [comment]
Hi,
I'm not familiar with anko DSL, however I noticed you're missing the 'type' attribute which is required. Maybe you could debug the StepperLayout in your configuration and see which line is failing?

**Comment by pauliusrum** [comment]
> however I noticed you're missing the 'type' attribute which is required. 

Yes, that's the problem. Now the only way to set it is through XML attributes. Would it be possible to make an additional constructor which takes the 'type' instead of AttributeSet object (since this is only used for XML and implementing the interface for regular use would not be efficient), because anko DSL builds the UI programmatically not through XML inflators.

**Comment by fabiozo** [comment]
@pauliusrum  It would be good if you create pull request with mentioned changes.

**Comment by zawadz88** [comment]
@pauliusrum creating a new constructor with the type parameter might not be a good long-term solution as probably other properties would be needed later on as well. Have you tried setting the type attribute in a style instead as e.g. here https://github.com/Kotlin/anko/issues/16 ? Alternatively, you could set in a theme as described here https://github.com/stepstone-tech/android-material-stepper/blob/master/README.md#using-same-stepper-styling-across-the-application ?

**Comment by pauliusrum** [comment]
> creating a new constructor with the type parameter might not be a good long-term solution as  probably other properties would be needed later on as well

Agree. 
Android native widgets expose setters for attributes e.g. Button exposes setters for text size, text color etc. since inflating the XML is more expensive then setting the properties programmatically, but since the layout in the stepper is inflated in the constructor we could not apply this approach.

Your later solution is good I will use it. Thank you for your help.

**Comment by seaskyways** [comment]
What i ended up doing is having the stepper alone in xml, and include it in my layout DSL
