### ISSUE TITLE
How to populate a second fragment based on selection in first fragment

### ISSUE THREAD

**Issue by praveenb** [stepstone-tech/android-material-stepper#114]
Hi , 

Thanks for the wonderful tool, impressive work. 

I've a scenario, say I've 3 fragments in the first fragment, I placed two radio buttons (Music, Books). Now, In the first fragment if user selected Music, app need to show MusicFragment. If user selected Books, app need to show Books fragment.

For this I've created a two step layout using the library. But i'm not able to show 2nd fragment based on user selection.

Hope it make sense.

Could you please help me on this.

Thank you.

**Comment by zawadz88** [comment]
Hi @praveenb, 
This is not possible with this library.
The reason for this is that some of the components like tab titles might be already displayed and it might be confusing to the user if they change.
So in other words, the lib expects the list of steps to be static.

If the number of steps does not change in your case you might consider using different child Fragments or Views and inflate them in the second step based on user selection though.

**Comment by praveenb** [comment]
Ok, Thanks for reply.
That idea worked for me.

Another question is,

When i use only one Fragment, in Step layout. Next button (or Complete button) is clickable but set as partial invisible status. 

How to make it visible.
Please let me know.

Thank you.

**Comment by zawadz88** [comment]
Hi,
You can change the color of the text color of the Next and Complete button by using custom view attributes - please see the readme for more details.
If the issue still occurs please file a new issue with more details, i.e. library version, your layout XML and how your adapters are configured, etc.
