### ISSUE TITLE
Is it possible to jump a to specific step?

### ISSUE THREAD

**Issue by lidox** [stepstone-tech/android-material-stepper#121]
Let's say I have 10 steps. Can I start the Wizzard on step 5?

**Comment by zawadz88** [comment]
Hi @lidox,
Yes, this is possible. You can either call `StepperLayout#setCurrentStepPosition (int)` after creating the adapter or set the initial step when setting the adapter by calling `StepperLayout#setAdapter(@NonNull StepAdapter stepAdapter, @IntRange(from = 0) int currentStepPosition)`
