### ISSUE TITLE
Issue on createStep() position

### ISSUE THREAD

**Issue by bruferrari** [stepstone-tech/android-material-stepper#122]
Hi, I'm tying to run the following code in my createStep() function but it's not working well, when it's start it takes the position 0 and 1 already and don't respect the fragments order.

```
override fun createStep(position: Int): Step {
        AppLog.d("position: " + position)

        when(position) {
            0 -> return NameFragment()
            1 -> return EmailFragment()
            2 -> return PasswordFragment()
            else -> throw IllegalArgumentException("Unsupported position: " + position)
        }

    }
```

I've found the issue #35 and now I got it the thing with ViewPager and so on, but how can I solve this? I need to follow an order to show the fragments, can you help me?

Thanks in advance.

**Comment by zawadz88** [comment]
Hi @bruferrari,
Could you provide more details i.e. steps to reproduce the issue and your expected result?
What do you mean by:

> I need to follow an order to show the fragments

?

**Comment by bruferrari** [comment]
Hi @zawadz88 I've found what's going wrong on my code, what I meant to say is that I needed an exhibition order for my fragments, I've found that I'm setting 5 as return for `getCount()` on my adapter and setting just 3 fragments what generates some kind of strange issue on `position` at `createStep()` function, but when I've reduced to 3 the return of `getCount()` everything worked fine.

I don't get why, but when the return of getCount is different than the number of fragments instantiated on `createStep` the position does not represents the fragment position itself.
