### ISSUE TITLE
How does android:orientation work on the widget?

### ISSUE THREAD

**Issue by tiagoalmeidagit** [stepstone-tech/android-material-stepper#124]
Had some problems I though it was not necessary, and nothing shows when it's horizontal.

**Comment by zawadz88** [comment]
Hi,
You shouldn't be using this attribute on this View. It works only in the vertical mode. If you look at `ms_stepper_layout.xml` you should see why nothing is shown.

What were you trying to achieve?

**Comment by tiagoalmeidagit** [comment]
Oh I understand the view extends LinearLayout, I think it would be best if you force vertical orientation in code, otherwise other developers might forget to add the attribute in the xml. 

Great lib thanks

**Comment by zawadz88** [comment]
Hi @tiagoalmeidagit,
This attribute shouldn't be needed at all when declaring a StepperLayout in your layout XML.
You're saying that if you don't specify it a horizontal orientation is used?

**Comment by tiagoalmeidagit** [comment]
Yes, 

in your getting started wiki the example has orientation vertical, I tried to remove it and had problems.
`
<?xml version="1.0" encoding="utf-8"?>
<com.stepstone.stepper.StepperLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/stepperLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    **android:orientation="vertical"**
    app:ms_stepperType="progress_bar" />
`

**Comment by zawadz88** [comment]
Wow, I can't believe we actually missed it :P This is definitely a bug.
Thank you for reporting this!
That's something we definitely have to fix.

**Comment by zawadz88** [comment]
The changes are already on master and will be released in the upcoming patch release.
@tiagoalmeidagit again thank you for reporting this
