### ISSUE TITLE
How to use Vertical Stepper as shown in the Image.

### ISSUE THREAD

**Issue by syedalinaqi** [stepstone-tech/android-material-stepper#128]
How can I use a vertical stepper like shown in this [image](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B7WCemMG6e0VTndyUnNCR2tQREE/components_steppers.png). I specified the orientation as `android:orientation="vertical"` but it still shows horizontal.

**Comment by zawadz88** [comment]
Hi,
This library supports only horizontal steppers. There are however other libraries that can help you achieve that effect as far as I know.

The orientation tag should be also removed, however this is currently on code review.
