### ISSUE TITLE
Hide Bottom Navigation

### ISSUE THREAD

**Issue by jboxx** [stepstone-tech/android-material-stepper#129]
I like the idea of this library, but any example to use without bottom navigation? So I need to hide bottom navigation and use programmatically process?

**Comment by zawadz88** [comment]
Hi @jboxx,
This is probably related to #108.
The library does not support this feature.
I can see however that this is a recurring request. Could you explain your use case for using this library without the bottom navigation?

**Comment by jboxx** [comment]
@zawadz88 I need to make next and back control action per Step fragment. There is an function to override next and back, so I can use it for toolbar home back navigation and an button to next a step inside content fragment. Maybe can be added to Step interface?

**Comment by zawadz88** [comment]
@jboxx so you basically would like to use your own buttons inside of each step fragment?
What features from this library are needed then? Can't you use a ViewPager instead?

**Comment by jboxx** [comment]
@zawadz88 I need to use the dynamic adapter and the validation, navigation interface, the animation also

**Comment by zawadz88** [comment]
Thanks for your feedback.
This is not really a part of the Material spec, however since it's not really a big change to make and this request comes up from time to time it's probably a good idea to add this feature.

A new attribute `ms_showBottomNavigation` could be added with the default being `true` + a corresponding setter & getter. And a sample :)

**Comment by kareem12599** [comment]
I try to add disable bottom navigation but it still doesn't work. 
Does the library support adding a custom button inside each step fragment to navigate to another step fragment?!

**Comment by zawadz88** [comment]
Hi,
This feature has not been implemented yet - hence the ticket hasn't been closed. I'll gladly review any PRs regarding this though.
As for the second question - step content is controlled by the developer and this shouldn't be done by the library as the content can be totally different and depends on the app. It's not also a part of the Material spec.

**Comment by yccheok** [comment]
Hi, currently, I'm studying how to simplify a account opening process, which requires extensive user inputs. 

I can provide a use case, where the ability to hide bottom navigation, in the middle of steps appear to be useful.

These is an example from a stock market app.

- Step 1 - Text input residential address

- Step 2 - Select country. Note, here's a good step, where we can hide the bottom navigation for 2 good reasons. (1) Provide more visualize area to useful content. (2) Unlike text input action, "select" action usually also indicate user is pretty confident on his selection. There's no need to provide another extra "NEXT" button to move to next step. Once select is performed, our code can programmatically move the user to next step. 

- Step 3 - Enter social security number. Here's, we should show the bottom navigation again.

![step0](https://cloud.githubusercontent.com/assets/308276/26818837/e2259ace-4ace-11e7-92e1-a76aee390778.png)

![step1](https://cloud.githubusercontent.com/assets/308276/26818849/ed180a48-4ace-11e7-8a57-fa2889bbb24d.png)

![step2](https://cloud.githubusercontent.com/assets/308276/26818859/f2bd42ba-4ace-11e7-8a86-62b7d4743f3c.png)

I hope this explains enough, the usefulness of providing capability to hide bottom navigation. 

@zawadz88 Can you kindly point me out which file I should modify, if I want to expose "hiding bottom navigation" API to the caller? Thank you very much

**Comment by zawadz88** [comment]
Hi @yccheok,
Thanks for the feedback! I agree that in the scenarios you provided it makes sense to hide it.
regarding the API changes I see that there's already a PR regarding this :)

**Comment by yccheok** [comment]
Thank you. I saw there's PR https://github.com/stepstone-tech/android-material-stepper/pull/137

**Comment by yccheok** [comment]
I forked and perform some modification, so that I can change the visibility of bottom navigation bar, in different page during

    @Override
    public void onStepSelected(int newStepPosition) {
        if (newStepPosition == 0) {
            this.mStepperLayout.setShowBottomNavigation(false);

https://github.com/yccheok/android-material-stepper/commit/09f41fc5e5b7d573f1839e59f117886cd80d18d1

**Comment by zawadz88** [comment]
Thank you all for participating. This is now released in `3.3.0`
