### ISSUE TITLE
Set colors programmatically

### ISSUE THREAD

**Issue by tobiasschuerg** [stepstone-tech/android-material-stepper#132]
Similar to `stepperLayout.setBackgroundColor(color)` there should be a method `stepperLayout.setButtonColor(color)`  or `stepperLayout.setTextColor(color)` to set the text color of a button color programmatically.

Although the above would be enough for my use case, as an alternative `StepViewModel` could have to two more fields `backButtonTextColor` and `nextButtonTextColor` to set the text color indivially for each step.

**Comment by zawadz88** [comment]
This should probably have two versions i.e. one taking a color int as a parameter and a second one with a `ColorStateList` param.
Could add more information on why would you like to have this feature implemented i.e. describe your use case a bit?

**Comment by tobiasschuerg** [comment]
The `stepperLayout.setTextColor(color)` would be enough for my use case. I just want to set the background color and according to that to retain readability I also need to adjust the textcolor.

**Comment by zawadz88** [comment]
But would you like to change the background color of the buttons per step as well? Or the entire bottom navigation bar?

**Comment by NeoDigi** [comment]
I would really want that, I need to change the color of the bottom bar programatically as well as the button and the active step color, for business reason, I'll sometime receive a color via a webservice and I need to use this color to "theme" the application.

**Comment by Rainer-Lang** [comment]
Any news?

**Comment by zawadz88** [comment]
Hi @Rainer-Lang,
So I haven't really had time to address this so far, but any contributions are welcome!

**Comment by zawadz88** [comment]
I've added this and it's available on the `develop` branch currently. It will be released in `4.3.0` shortly.

Thanks all for contributing!

**Comment by Rainer-Lang** [comment]
@zawadz88 Thanks - i'll test it when 4.3.0 is released.
