### ISSUE TITLE
Use StepperLayout as stand-alone with its height to wrap_content

### ISSUE THREAD

**Issue by tobiasschuerg** [stepstone-tech/android-material-stepper#133]
If I set up a layout and set the StepperLayout to align at the bottom and with `height="wrap_content"` the StepperLayout fills the whole parent.

I would like to only use the stepper for updating a reyclerview and not to use fragments. Is there a way to use the StepperLayout stand-alone without Viewpager and stuff?

### example:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <android.support.v7.widget.RecyclerView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:background="#200f"/>

    <com.stepstone.stepper.StepperLayout
        android:id="@+id/stepper_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:layout_weight="0"
        android:background="#e99"
        android:gravity="end"
        app:ms_stepperType="dots"/>

</LinearLayout>
```

results into 

![image](https://cloud.githubusercontent.com/assets/1324555/26552018/a8656c28-4485-11e7-8af9-18abc453b2e1.png)

although I would expect it to be:

![image](https://cloud.githubusercontent.com/assets/1324555/26552052/c6a780ea-4485-11e7-9c2a-04334b44d45b.png)

what I only get if setting `android:layout_height="48dp"` explicitely.

**Comment by zawadz88** [comment]
Hi @tobiasschuerg,
This is not really in scope of this library. You could probably edit the StepperLayout and remove ViewPager and the rest of the stuff you don't really need, but I cannot think of an easy way to do this.

**Comment by tobiasschuerg** [comment]
Although not nice, I just went with `findViewById(R.id.ms_stepPager).setVisibility(View.GONE);`
