### ISSUE TITLE
Create ListView From Passed Data

### ISSUE THREAD

**Issue by riddict** [stepstone-tech/android-material-stepper#135]
Hello Everyone
I have this step where users passed a string of data containing "@" character and in the second step i split the passed data and create an array where I display it in a custome ListView. I implement the logic in onSelect method but after testing my app crash.
this is my code in onSelect method
```
passedData = dataManager.getData();
		String[] arrayLfl = passedData.split("@");
		ListAdapter adapter = new ArrayAdapter<String>(getActivity(), R.layout.quick_lfl_row, R.id.absenLflList, arrayLfl);
        ListView listView = (ListView) getView().findViewById(R.id.list_lfl);
		listView.setAdapter(adapter);
```

Please help me find what I do wrong. thanks.

**Comment by zawadz88** [comment]
Hi @riddict,
Please provide the stacktrace of the crash - otherwise it's hard to figure out what went wrong.

**Comment by riddict** [comment]
thanks @zawadz88
yes right, I forgot
here is my log cat
```
06-03 19:53:10.246 E/AndroidRuntime(2162): Process: tk.divabyan.ig, PID: 2162 06-03 19:53:10.246 E/AndroidRuntime(2162): at tk.divabyan.ig.activity.QuickLfl.FragmentStep2.onSelected(FragmentStep2.java:76) 06-03 19:53:10.246 E/AndroidRuntime(2162): at tk.divabyan.ig.activity.FragmentStep1.onNextClicked(FragmentStep1.java:68)
```

**Comment by riddict** [comment]
I am sorry, my mistake
Give a wrong resource id.
