### ISSUE TITLE
change Step Title in Tabview at run time.

### ISSUE THREAD

**Issue by pouriabagheri** [stepstone-tech/android-material-stepper#138]
I am working on the material stepper with Tabs 
I was wondering if there is a way to show the tab's title only when that specific tab is on screen.
basically show the rest of the tabs only by number and **no title**. 

![screenshot_1496728934](https://cloud.githubusercontent.com/assets/5735478/26815962/f39037f6-4a97-11e7-8060-c77423d44a95.jpg)

**Comment by zawadz88** [comment]
Hi,
I cannot really think of an easy way to do this right now.
You might try updating the adapter when a new step is selected so that it returns the title in `StepViewModel` only for the selected step?

**Comment by pouriabagheri** [comment]
I've been thinking about the same: in sample app gives an example of how to set the title for each tab separately. but from my understanding the adapter is called only in start ` @Override
        public StepViewModel getViewModel(@IntRange(from = 0) int position) {` is only called at start and not every time we switch between steps. 
is there a way to update the StepVIewModel Title in run time ?

**Comment by zawadz88** [comment]
@pouriabagheri 
The tab titles are updated when a new adapter is set.
`StepperLayout#setAdapter(StepAdapter)` -> `TabsStepperType#onNewAdapter(StepAdapter)` -> `TabsContainer#setSteps(List<CharSequence>)`.
You might try setting a new adapter (with the only difference being the updated `StepViewModel` per step), however I'm not sure whether this won't cause any side effects e.g. step fragments loosing some data, etc.

**Comment by pouriabagheri** [comment]
@zawadz88 I am a bit confused. from what i have understood the stepper first gets Titles from
`@NonNull
        @Override
        public StepViewModel getViewModel(@IntRange(from = 0) int position)`
and after getting all the titles it will call
`public Step createStep(int position)`  -- for n and n+1 positions if any.
then it will call 
`@NonNull
        @Override
        public StepViewModel getViewModel(@IntRange(from = 0) int position)`
again for first position only (the first step's title). 

and when we move to step 2 it will call 
`@NonNull
        @Override
        public StepViewModel getViewModel(@IntRange(from = 0) int position)`
only for title n+1

so it seems not possible to modify the title from adapter based on position of the stepper.
maybe i'm missing something somewhere. 

Note: as i mentioned in last comment the code is running but it doesn't change the titles.

**Comment by zawadz88** [comment]
@pouriabagheri The tab titles are updated ONLY when a new adapter is set.
They are not updated when you actually change the step - please see usage of `StepAdapter#getViewModel(int)`.
While `StepAdapter#getViewModel(int)` gets called once you to a different step, the returned data is not used to change the step title, but to e.g. change the text of the Next button.

So in short - the current implementation does not allow you to achieve what you're trying to achieve.

What I'm suggesting as a workaround is to store the currently selected step in an adapter and return the title only for the selected step. However, for this to work you would also need to tell StepperLayout to refresh the titles. To achieve that you could possibly call `stepperLayout.setAdapter(stepperLayout.getAdapter())`, however as I said earlier it might cause some side effects.

**Comment by pouriabagheri** [comment]
@zawadz88 Thank you i have understand the situation now .

**Comment by awaisaliliaqat** [comment]
> @zawadz88 Thank you i have understand the situation now .

@pouriabagheri Can you share the final code
