### ISSUE TITLE
Is there a way to go to the N step page directly programatically?

### ISSUE THREAD

**Issue by yccheok** [stepstone-tech/android-material-stepper#139]
We have a wizard which provides account opening feature.

Say, the wizard has 10 step pages.

When user is in 6th step page, he press home button to give up account opening process.

When user comes back to our app, we would like to resume the account opening process, by bring the user directly back to 6th step page.

Currently, may I know is there any API to do so?

**Comment by zawadz88** [comment]
Hi @yccheok,
It's possible. Please see #121

**Comment by yccheok** [comment]
Sorry @zawadz88 I should check it more thoroughly on `StepperLayout#setCurrentStepPosition (int)`
