### ISSUE TITLE
how can i use Horizontal stepper 

### ISSUE THREAD

**Issue by walaa118** [stepstone-tech/android-material-stepper#14]
what is the type for Horizontal stepper

**Comment by fabiozo** [comment]
Hi,

Horizontal stepper is called "DEFAULT TABS" or "STYLED TABS" in Sample app.

Here is an example how to created it from layout:

```
<?xml version="1.0" encoding="utf-8"?>
<com.stepstone.stepper.StepperLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/stepperLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    app:ms_stepperType="tabs" />

```

app:ms_stepperType="tabs" attribute is crucial here.

**Comment by walaa118** [comment]
how can i use it in the fragment ?

**Comment by WhySoMadBruh** [comment]
how to add more then one fragment in MyStepperAdapter calss

**Comment by NehaSingh222** [comment]
I want to remove shadow from horizontal stepper, I already tried elevation but didn't work. please help me
