### ISSUE TITLE
Support for multilanguage

### ISSUE THREAD

**Issue by catarinaclss** [stepstone-tech/android-material-stepper#145]
I'm trying to overwrite these strings to translate them, but it's not working.

```
 <string name="ms_prev">PREV</string>
 <string name="ms_next">NEXT</string>
 <string name="ms_end">COMPLETE</string>
 <string name="ms_continue">CONTINUE</string>
 <string name="ms_optional">Optional</string>
```

Anyone can help?

**Comment by zawadz88** [comment]
Hi @catarinaclss,
Please provide more details i.e. where are you trying to overwrite them and how are you trying to do this now? Also, what are you trying to achieve? Also, I don't know what `ms_optional` and `ms_continue ` are - they not a part of this library.

**Comment by catarinaclss** [comment]
Hi @zawadz88 

I saw those strings on the deprecated library documentation. I would like to know how to translate the texts of the buttons: back, next and complete. Which strings (string_name) should I put on my strings.xml file?

`<string name="string_name">text_string</string>`

**Comment by zawadz88** [comment]
You can change these strings by setting `ms_backButtonText`, `ms_nextButtonText` and `ms_completeButtonText` attributes on the StepperLayout in your layout XML. Please see: https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/res/layout/activity_styled_progress_bar.xml

**Comment by catarinaclss** [comment]
Thank you @zawadz88
