### ISSUE TITLE
Creating two fragments

### ISSUE THREAD

**Issue by borovskym** [stepstone-tech/android-material-stepper#148]
Hello, I am working on app with this library and I run into a problem.

First at all, I parse XML file into an recyclerview and after click on item new Activity is opened where is stepperLayout with attached adapter. In adapter class I am checking in switch which fragment application should create.  Then, it creates a new fragment and pass data into it by sharedpreferences. In fragment I parse json string into Class object and init UI. Also I am sending data by SP into Adapter, there I am sending List of mentioned class Objects. Everything looks that works great except that, the first object in list is like skipped. I logged it into Logcat and its sended, parsed and even fragment is created but the UI is not like its supposed to be, its showing for the first and second steps the same fragment and then the third, also when I proceed to second fragment I see in logcat that data for the third fragment cames.

I can send you git link if you want to look at code, just contact my on email: misoborovsky@gmail.com

Thanks for respond and have a nice day!

**Comment by zawadz88** [comment]
Hi,
Please post the code here. Also, please bear in mind that StepperLayout uses a ViewPager underneath. So in ViewPager the fragment to the left and to the right are also created even if you only see the fragment in the middle.

**Comment by borovskym** [comment]
Hello, the problem were solved. There was a problem with shared preferences I replaced it with function in adapter and its working now. Thanks for respond anyway.
