### ISSUE TITLE
share data between steps 

### ISSUE THREAD

**Issue by walaa118** [stepstone-tech/android-material-stepper#15]
how can i share data between tabs steps?

**Comment by zawadz88** [comment]
The steps are internally regular Fragments set in a ViewPager. Therefore, you could share the data between them as you would normally do in such a scenario, e.g. have a context singleton holding all that data, keep it in an activity or if you'll more interested in say passing some data from step A to step B you could also fire e.g. a broadcast or an Eventbus event with that data.
