### ISSUE TITLE
Does it make sense to provide ms_showStepper?

### ISSUE THREAD

**Issue by yccheok** [stepstone-tech/android-material-stepper#154]
Hi,

Currently, I do have a requirement where I need to hide the default stepper, and using my own custom progress bar.

This is how it looks like

![screenshot_20170624-135536](https://user-images.githubusercontent.com/308276/27506165-5dfb7168-58e5-11e7-868a-582a03001b5f.png)

This is my change on how I did it.

https://github.com/yccheok/android-material-stepper/commit/acecf3c5fd1102b63aa73ad988f907db581bf424

Does it make sense to you? If you, I'm more than happy to send a pull request.

Thank you.
Cheok

**Comment by zawadz88** [comment]
Hi @yccheok,
I think it makes sense to add such an option.
I'm wondering whether it wouldn't be better if this could be handled via a new stepper type though, e.g. `none`. What do you think?

**Comment by yccheok** [comment]
Yes. Having "none" makes sense :) 👍

**Comment by yccheok** [comment]
I had made change on `none` type

https://github.com/yccheok/android-material-stepper/commit/0a06894cab063dfd488c8f4db91e44321ece50e0

I'm more than happy to send a PR if you like the change. Unfortunately, since I'm not able to configure unit test to run properly in my local, I'm not able to write a test for it.

**Comment by zawadz88** [comment]
Please do :) I'll gladly review it and add it to the project.
Thanks!

**Comment by zawadz88** [comment]
Hi @yccheok,
I've added the missing tests and a sample. 
Thanks for contributing!

**Comment by zawadz88** [comment]
Merged to develop, this will be a part of the next release.
