### ISSUE TITLE
Problem when switching stepper layout adapters

### ISSUE THREAD

**Issue by dotocan** [stepstone-tech/android-material-stepper#155]
Hi,
in my app, I need to show two steppers one after another in the same activity. User must first complete 5 steps (selecting and evaluating Point of Sale, or Pos as seen in code) , and after clicking finish, I need to replace current 5-step stepper with new 2-step one (selecting and evaluating vendor who works in previously evaluated point of sale).
I tried creating two different adapters:

```
    override fun populatePosFragments() {
        val posAdapter = EvaluationPosAdapter(supportFragmentManager, this, screens)
        stepper_layout.setAdapter(posAdapter, startingStepPosition!!)
    }

    override fun populateVendorFragments() {
        val vendorAdapter = EvaluationVendorAdapter(supportFragmentManager, this, screens)
        stepper_layout.setAdapter(vendorAdapter, startingStepPosition!!)
    }
```

I do get two steps after calling second method, but the two fragments inside it are actually the first two fragments from first adapter. Check the code below. EvaluationVendorAdapter should show only two steps, and in those steps should be VendorStepFragment and EvaluationStepFragment, but instead, I do get two steps, and their titles are fine (using tab version of stepper), but fragments inside those steps are actually Region and Partner step fragment from the first adapter. Here are my adapters:

```
class EvaluationPosAdapter (fm: FragmentManager, context: Context, val screens: List<Screen>)
    : AbstractFragmentStepAdapter(fm, context) {

    override fun createStep(position: Int): Step {

        when (position) {
            0 -> return SelectRegionStepFragment.newInstance()
            1 -> return SelectPartnerStepFragment.newInstance()
            2 -> return SelectPosTypeStepFragment.newInstance()
            3 -> return SelectPointOfSaleStepFragment.newInstance()
            4 -> return EvaluationStepFragment.newInstance(screens[0], EvaluationRequestType.SUBMIT_POS_EVALUATION)
        }

        return SelectRegionStepFragment.newInstance()
    }

    override fun getCount(): Int {
        return 5
    }

    override fun getViewModel(position: Int): StepViewModel {
        var title: String = context.getString(R.string.select_region)
        when (position) {
            0 -> title = context.getString(R.string.select_region)
            1 -> title = context.getString(R.string.select_partner)
            2 -> title = context.getString(R.string.select_pos_type)
            3 -> title = context.getString(R.string.select_point_of_sale)
            4 -> title = screens[0].name
        }
        return StepViewModel.Builder(context).setTitle(title).create()
    }
}
```

```
class EvaluationVendorAdapter (fm: FragmentManager, context: Context, val screens: List<Screen>)
    : AbstractFragmentStepAdapter(fm, context) {

    override fun createStep(position: Int): Step {

        when (position) {
            0 -> return SelectVendorStepFragment.newInstance()
            1 -> return EvaluationStepFragment.newInstance(screens[1], EvaluationRequestType.SUBMIT_VENDOR_EVALUATION)
        }

        return SelectVendorStepFragment.newInstance()
    }

    override fun getCount(): Int {
        return 2
    }

    override fun getViewModel(position: Int): StepViewModel {
        var title: String = context.getString(R.string.select_vendor)
        when (position) {
            0 -> title = context.getString(R.string.select_vendor)
            1 -> title = screens[1].name
        }
        return StepViewModel.Builder(context).setTitle(title).create()
    }
}
```

**Comment by zawadz88** [comment]
Hi @dotocan,
Thanks for reporting this. I'm not sure whether the underlying `FragmentManager` doesn't keep references to the old adapter somehow which might be causing this.
Anyway, the library should not behave like this.
I'll investigate.

**Comment by zawadz88** [comment]
Hi @dotocan,
First of all sorry for the late response. I've found the following workaround based on https://stackoverflow.com/a/20068511/973379:

```    
    override fun onCompleted(completeButton: View?) {
        println("onCompleted")
        removeOldFragments()
        mStepperLayout.setAdapter(PassDataBetweenStepsFragmentStepAdapter(supportFragmentManager, this), 0)

    }

    private fun removeOldFragments() {
        supportFragmentManager.fragments?.let {
            val fragmentTransaction = supportFragmentManager.beginTransaction()
            it
                    .filter { it is Step }
                    .forEach { fragmentTransaction.remove(it) }


            fragmentTransaction.commitNow()
        }

    }
```
So basically you need to remove the old fragments before setting the new adapter. 
Now, I wouldn't want to add it to the library itself since:
1. the workaround is a bit hacky
2. the adapter you set doesn't have to be a fragment adapter
3. theoretically you might have other fragments which implement Step in the current Activity and you don't want them to be removed.

Please let me know if this helped.

**Comment by dotocan** [comment]
This does the job, thank you.

**Comment by kyao-Frndz** [comment]
Hi zawadz88, I am facing the same problem as @dotocan but I am calling the stepper within another fragment which works with Navigation Drawer. I have tried your workaround solution but it didn't work.

**Comment by zawadz88** [comment]
Hi @kyao-Frndz,
It might be an issue with a different FragmentManager. If you use the Material stepper within a Fragment then you should be probably using this Fragment's child fragment manager and not the Activity's fragment manager.

**Comment by kyao-Frndz** [comment]
Hi @zawadz88, thanks for the response. You were right, I was using the main fragment manger instead the child one. 
Thanks again
