### ISSUE TITLE
Is there a way to change number of steps dynamically.

### ISSUE THREAD

**Issue by yccheok** [stepstone-tech/android-material-stepper#156]
I was wondering. Is there any way to change number of steps dynamically. I have the following use case.

Currently, I'm in the 2nd page out of total 3 pages.

![0](https://user-images.githubusercontent.com/308276/27584717-8d30ac4a-5b6b-11e7-968f-efead44abcd6.png)

When the check box is ticked, I would like the 2nd page to be the last page.

![1](https://user-images.githubusercontent.com/308276/27584733-a2eeb360-5b6b-11e7-815e-91dca971263f.png)

I have the following code snippet. It is able to change the NEXT button to DONE button

        addDocumentStepperAdapter.setPhotoIdContainsProofOfAddress(photoIdContainsProofOfAddress);
        addDocumentStepperAdapter.notifyDataSetChanged();
        mStepperLayout.setCurrentStepPosition(currentStepPosition);

    public class AddDocumentStepperAdapter extends AbstractFragmentStepAdapter {
        @Override
        public int getCount() {
            if (photoIdContainsProofOfAddress) {
                return 2;
            } else {
                return 3;
            }
        }

        public void setPhotoIdContainsProofOfAddress(boolean photoIdContainsProofOfAddress) {
            this.photoIdContainsProofOfAddress = photoIdContainsProofOfAddress;
        }

The shortcoming is, view pager indicator is not updated to reflect total of pages. Is there any way to update view pager indicator properly?

**Comment by zawadz88** [comment]
Hi @yccheok,
I think this might be related to #39 
You might try the solution posted there, although personally I would rethink the UI here.
It probably will be confusing to the user if we showed that there are 2 steps and then changed it e.g. to two.

**Comment by yccheok** [comment]
Hi @zawadz88 

Thanks for the info.

Indeed, we did a hacky way on the forked version

https://github.com/yccheok/android-material-stepper/commit/45927f457e536d76a6cd10ff0d6a666f91c9793e

    public void setPhotoIdContainsProofOfAddress(boolean photoIdContainsProofOfAddress) {
        addDocumentStepperAdapter.setPhotoIdContainsProofOfAddress(photoIdContainsProofOfAddress);
        addDocumentStepperAdapter.notifyDataSetChanged();
        mStepperLayout.setCurrentStepPosition(currentStepPosition);
        mStepperLayout.refreshSteperType();
    }

**Comment by zawadz88** [comment]
Hi @yccheok,
You would probably need to add some logic for other stepper types to refresh themselves as well.
Although, as I said earlier I think this is confusing to the user so I'm a bit reluctant to enable such a functionality in the library TBH.

**Comment by yccheok** [comment]
Hi @zawadz88 

No problem at all. I can fully understand your concern. Such requirement is quite an edge case, and might not appeal from library designer point of view.

Since such "hack" fit to our project requirements, currently, we just use the library from my "hacked" forked branch. Works perfectly fine at this moment and I hope that able to make our customer happy. (Not released to production yet, but we are close...)

compile 'com.github.yccheok:android-material-stepper:0.3'

Thank you very much.

**Comment by intothevoid1986** [comment]
> Hi @zawadz88
> 
> No problem at all. I can fully understand your concern. Such requirement is quite an edge case, and might not appeal from library designer point of view.
> 
> Since such "hack" fit to our project requirements, currently, we just use the library from my "hacked" forked branch. Works perfectly fine at this moment and I hope that able to make our customer happy. (Not released to production yet, but we are close...)
> 
> compile 'com.github.yccheok:android-material-stepper:0.3'
> 
> Thank you very much.

You saved my ass maaan!

Thank you!
A.
