### ISSUE TITLE
How to include this project in an existing android project in Android Studio

### ISSUE THREAD

**Issue by vega25** [stepstone-tech/android-material-stepper#159]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [ ] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

**Comment by zawadz88** [comment]
Hi @vega25,
You should add it to your project's Gradle dependencies as described here: https://github.com/stepstone-tech/android-material-stepper/blob/master/README.md#getting-started

**Comment by vega25** [comment]
I have downloaded the Zip- Unzipped it and added as a new module to my project.
Tried the method described also.

I am getting Error:(2, 0) Plugin with id 'kotlin-android' not found.
File:F:\Work\AndroidProjs\DeviceChk\material-stepper\build.gradle">

Could you please guide me where I am wrong.
Thanks for the help.

**Comment by zawadz88** [comment]
@vega25,
Is there any specific reason why you cannot use as a Gradle dependency instead?
If you want to use it as a submodule in your project directly by copying it into your project you'll need to update `build.gradle` file in `material-stepper` dependency to actually work with your project.
If you want to use the library as it is without any modifications then adding it as a Gradle dependency is the preferred way.

**Comment by vega25** [comment]
Thanks for the help.
All the samples are in kotlin language, are there any samples which are not in kotlin language?

**Comment by zawadz88** [comment]
All the samples were migrated to Kotlin recently, but you can see the older version written in Java here: https://github.com/stepstone-tech/android-material-stepper/tree/v3.2.0/sample/src/main/java/com/stepstone/stepper/sample
