### ISSUE TITLE
in Horizontal stepper , how can i prevent tab reload in tab selected 

### ISSUE THREAD

**Issue by walaa118** [stepstone-tech/android-material-stepper#16]
when i have three tabs , 
select tab two then reload tab one how can i prevent the loading.

**Comment by zawadz88** [comment]
I do not really understand the issue you're having TBH. Could you elaborate please? What do you mean by reloading/loading? Are some of the methods in the step fragments being called when they are not supposed to? If so, could you please say which ones?

**Comment by zawadz88** [comment]
@walaa118 Could you please provide an example?
