### ISSUE TITLE
Subtitle for tab stepper

### ISSUE THREAD

**Issue by vmzdl** [stepstone-tech/android-material-stepper#160]
Hi, I wonder if there is a possibility to put a subtitle under the tab stepper title, as shown in this Google Material image [here](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B7WCemMG6e0VZDNSY2lFWWdDWm8/components_acux_stepper_optstps.png), to put a tab as 'optional' as in the example.

And also as an error/alert message like [here](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B7WCemMG6e0VMWxJVzRSTGFfTGc/components_acux_stepper_altlblplerr_rl.png).

**Comment by zawadz88** [comment]
Hi @vmzdl,
This is not possible in the library currently, but it would definitely be a nice enhancement!

**Comment by vmzdl** [comment]
I don't know if it would take too long to do, but if anyone could help it would be great, I'm kind of out of time to study all the code and start developing something. Thanks in advance =)

**Comment by zawadz88** [comment]
Almost done in https://github.com/stepstone-tech/android-material-stepper/tree/feature/issue-160 although I'll need to add unit & integration tests before this can get merged to `develop` and then released.

**Comment by zawadz88** [comment]
On `develop`, this will be in the next release!
