### ISSUE TITLE
How to set callback.goToNextStep(); in my custom click in fragment ?

### ISSUE THREAD

**Issue by ibrahimAlii** [stepstone-tech/android-material-stepper#161]
I wanna reach next step after click on my custom button in fragment, something like that :

` myButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                callback.goToNextStep(); 
            }
        });`

and as expected it's throw null, any help will appreciated.

**Comment by zawadz88** [comment]
Hi,
In order to go to the next step you might want to use something different. Please have a look at https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/step/fragment/FormStepFragment.kt (on some action in fragment you call a method on an interface which the containing activity implements) and https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/ProceedProgrammaticallyActivity.kt (to proceed you call `StepperLayout#proceed()`

**Comment by ibrahimAlii** [comment]
@zawadz88  Thanks for reply but i already did that, with no action, here is my code.. what i'm missing ?

**My activity:**

` private StepperLayout mStepperLayout;
    private static final String CURRENT_STEP_POSITION_KEY = "position";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_registration);
        mStepperLayout = (StepperLayout) findViewById(R.id.stepperLayout);
        int startingStepPosition = savedInstanceState != null ? savedInstanceState.getInt(CURRENT_STEP_POSITION_KEY) : 0;
        mStepperLayout.setAdapter(new MyStepperAdapter(getSupportFragmentManager(), this), startingStepPosition);
        mStepperLayout.setListener(this);
    }

 @Override
    public void onProceed() {
        mStepperLayout.proceed();
    }`

**My fragment:**

`@Nullable
    private OnProceedListener onProceedListener;

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnProceedListener) {
            onProceedListener = (OnProceedListener) context;
        }
    }

    private void goToNext() {
        if (onProceedListener != null) {
            onProceedListener.onProceed();
        }
    }

 sendCode.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mobile = phoneNum.getText().toString();
                if (isVaildPhone(mobile)) {
                    prefManager.setMobileNumber(mobile);
                    //requestForSMS(mobile);
                    //goToNext();
                    Toast.makeText(getActivity(), "clicked", Toast.LENGTH_SHORT).show();
                    goToNext();
                    //stepLayout.proceed();

                }
            }
        });
`

**My Adapter:**

` private static final String CURRENT_STEP_POSITION_KEY = "position";

    Context context;
    PrefManager pref;
    public MyStepperAdapter(FragmentManager fm, Context context) {
        super(fm, context);
        this.context = context;
        pref = new PrefManager(context);
    }

    @Override
    public Step createStep(int position) {
        final StepFragmentRegist1 step = new StepFragmentRegist1();
        final StepFragmentRegist2 step2 = new StepFragmentRegist2();
        final VerifyFragment verifyFragment = new VerifyFragment();
        final VerifyCode verifyFragment2 = new VerifyCode();
        pref = new PrefManager(context);
        if(pref.isWaitingForSms()){
            return verifyFragment2;
        }
        switch (position){
            case 0:
                return step;
            case 1:
                return step2;
            case 2:
                return verifyFragment;
            case 3:
                return verifyFragment2;

        }
        Bundle b = new Bundle();
        b.putInt(CURRENT_STEP_POSITION_KEY, position);
        step.setArguments(b);
        step2.setArguments(b);
        verifyFragment.onSaveInstanceState(b);
        verifyFragment.setArguments(b);
        verifyFragment2.setArguments(b);
        return null;
    }

    @Override
    public int getCount() {
        return 4;
    }

    @NonNull
    @Override
    public StepViewModel getViewModel(@IntRange(from = 0) int position) {
        //Override this method to set Step title for the Tabs, not necessary for other stepper types
        return new StepViewModel.Builder(context)
                .setTitle(R.string.tab_title) //can be a CharSequence instead
                .create();

    }
}`

**Comment by zawadz88** [comment]
Have you tried debugging the app? Does `onProceed()` get actually called? Where does the flow stop when you're debugging it?
Also, you posted the code of your fragment yet I see in step adapter that you're 4 different fragments?
Your `createStep` method also looks a bit suspicious (the part below the switch statement)

**Comment by ibrahimAlii** [comment]
@zawadz88   Well, Thanks for response, I'm make all correct, but i was missing `callback.goToNextStep();` in `onNextClicked` method so the listener didn't response for my action, It's worked now.
