### ISSUE TITLE
Why all fragment in the same adapter effected from process i makes in one of them in my `onCreatView`?

### ISSUE THREAD

**Issue by ibrahimAlii** [stepstone-tech/android-material-stepper#166]
I'm wondering why all fragment effected if i have some thing to do in one of them in `onCreatView` method, How i can avoid this from happening?

**Comment by zawadz88** [comment]
Hi @ibrahimAlii,
What do you mean exactly by that? Could you share some code and provide steps to reproduce?

**Comment by ibrahimAlii** [comment]
@zawadz88  suppose i have 3 fragment F1, F2, F3. and i have a timer or thread i start it in my `onCreatView` method in F3, Then the time or counter whatever should start after i open F3, but that dosen't happen, It's start after i start F1, is that normal? should i add break or something in my adapter?

**Comment by zawadz88** [comment]
Hi @ibrahimAlii,
You shouldn't do that in `onCreateView` as the underlying `ViewPager` creates the `Fragment`s next to the currently selected `Fragment` as well. If you want to do something when the `Fragment` gets selected I'd do that in `Step#onSelected()` in that Fragment.
