### ISSUE TITLE
Change height of tabs

### ISSUE THREAD

**Issue by pelirroja191186** [stepstone-tech/android-material-stepper#174]
Hello, 
Can anybody help me with this?
How cam i change the height of tabs?
Is it possible?
Thanks

**Comment by zawadz88** [comment]
Hi,
You can use your own style for every inner view of StepperLayout. You can checkout the sample app where a custom theme is used: https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/res/values/styles.xml https://github.com/stepstone-tech/android-material-stepper/blob/master/README.md#stepperlayout-style-attributes
Alternatively, you can simply overwrite the default with the following dimen in your app: 
`<dimen name="ms_step_tab_height">72dp</dimen>`

**Comment by pelirroja191186** [comment]
thanks very much, i solved

**Comment by grabcityinfo** [comment]
I would like to remove the bottom border from the tabs. How do I do this?

**Comment by grabcityinfo** [comment]
Hello zawadz88! I have found the answer. Thanks alot
