### ISSUE TITLE
Question: Does this stepper do vertical orientation with tabs?

### ISSUE THREAD

**Issue by rebdev** [stepstone-tech/android-material-stepper#175]
Can this stepper display numbers and tabs stacked vertically down the page when in vertical orientation? Like this:

![components_steppers](https://user-images.githubusercontent.com/1059668/29052437-70bf65e6-7c2d-11e7-93c4-21214089f5f5.png)

Vertically is how steppers are portrayed in the first examples in the Material guidelines, but I notice the only vertical steppers shown in this repository's examples have a sideways movement not a vertical one. Does it do vertical too?

**Comment by zawadz88** [comment]
Hi,
This library supports only horizontal steppers. There were some open source libraries which support vertical ones though the last time I checked.

**Comment by rebdev** [comment]
Okay, thanks for getting back to me so quickly!
