### ISSUE TITLE
compile failed version 4.0.0 

### ISSUE THREAD

**Issue by mobyqll1102** [stepstone-tech/android-material-stepper#176]
compile version 4.0.0  take a long time but failed

**Comment by zawadz88** [comment]
Hi,
Could you provide more details so that we can help, please? Are you compiling the sample or using the library in your project? What's the error? What build tools/support library are you using?

Without these it will be hard to help.

**Comment by mobyqll1102** [comment]
my build tools 25.0.2 ,i using the library 4.0.0 in project  when  build take a long time until
 failed .   using the library  3.3.0 can success

**Comment by zawadz88** [comment]
Can you post the stack trace of the error? What exactly is failing?
If you're missing the stack trace you can do the following:
`./gradlew assembleDebug --stacktrace`

**Comment by mobyqll1102** [comment]
this is error:Failed to resolve: com.android.support:appcompat-v7:25.4.0 
but my Repository version is latest. what's meaning?

**Comment by zawadz88** [comment]
Hi,
This is due to the changes in downloading support libraries. Please see: https://issuetracker.google.com/issues/62830109

**Comment by mobyqll1102** [comment]
@zawadz88 thanks  very much
