### ISSUE TITLE
How to make stepper RTL 

### ISSUE THREAD

**Issue by monajafi** [stepstone-tech/android-material-stepper#177]
How should I change the gravity of material-stepper to right. I want to change the orientation to RTL even if my device's language is set to english

**Comment by zawadz88** [comment]
Hi @monajafi,
I'm have little experience with RTL to be honest, however I assume this should work as any other view. So if you're able to force RTL on any view then it should also work for `StepperLayout`.
Maybe this would work: https://stackoverflow.com/questions/30241405/android-application-force-rtl ?

**Comment by monajafi** [comment]
Hi @zawadz88 
Great help, you saved my day, I'll try thanks

**Comment by monajafi** [comment]
I tried this, but setLayoutDIrection(rtllocale) is just working in api >= 17 still we have to change the layout direction in code. How should I make the stepper from right to left even if my device language is set to ltr

**Comment by zawadz88** [comment]
Hi,
I couldn't find anything else which would be a quick solution for this. If you can't have a min SDK 17 then the only other thing I see is for you to fork this library and change the layout files to be RTL only i.e. change `layout_marginLeft/Start` to `layout_marginRight` etc. 
It seems like there is no easy way to do this in Android...

**Comment by monajafi** [comment]
Thanks for your help
