### ISSUE TITLE
NOT BUG, need help, how to navigate steps dynamically

### ISSUE THREAD

**Issue by willemevenwel** [stepstone-tech/android-material-stepper#179]
Hi,

How do I manually navigate to a desired step (index), or the next step, or the previous step.

I noticed on the StepperLayout instance i can call mStepper.proceed() and that moves to next step.

The reason is I want to hide the bottom navigation control and implement previous and next buttons on either side of the stepper layout. And on clicking those buttons have the desired effect on the stepper reflect previous or next.

Regards,

Willem

Make sure these boxes are checked before submitting your issue - thank you!

- [x] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [x] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

**Comment by zawadz88** [comment]
Hi,
You can call `StepperLayout#setCurrentStepPosition(int)`.
Just remember that this does not verify the steps.
Please let me know if it helped.

**Comment by willemevenwel** [comment]
This related to me having a stepper inside a stepper. And therefore the inner steppers bottom navigation need not show, because navigation is done with a < and > button on either side of the inner stepper. And those on click events need to navigate the inner stepper.

The proposed way above does handle this. But I ended up using a AdapterViewFlipper for the inner stepper instead, and this works better.

Do you guys have functionality or examples of a stepper within a stepper. For instance a stepper with progress bar within a stepper tab or dots?

**Comment by zawadz88** [comment]
We don't really have an example of nested steppers, but from the UX perspective it doesn't really seem to me like a good idea to nest those TBH. 
It even says so in the Material doc: 
"Don’t embed steppers within steppers or use multiple steppers on one page."

**Comment by WhySoMadBruh** [comment]
Can you please upload a simple sample of the app covering all its features with java.
