### ISSUE TITLE
Is it possible to show BACK button in the first page of the wizard

### ISSUE THREAD

**Issue by yccheok** [stepstone-tech/android-material-stepper#18]
Hi,

Thanks for the great library!

I was wondering, is it possible to show BACK button in the first page of the wizard. The purpose of BACK button in the first page, is to close the entire wizard.

Thank you.

**Comment by zawadz88** [comment]
This is a valid request :) We'll look into this, however I cannot give you an approximate of the release date for this ATM.

**Comment by yccheok** [comment]
Thank you. Looking forward the update. After spending a day to integrate the library into our app, we are pretty happy with the outcome so far.

Thanks for the great library!

![screenshot_20161023-041045](https://cloud.githubusercontent.com/assets/308276/19622220/6c86e1c8-98d7-11e6-8083-644dc44811be.png)

![screenshot_20161023-040917](https://cloud.githubusercontent.com/assets/308276/19622222/717eb99e-98d7-11e6-955a-4fd5babb9d33.png)

**Comment by zawadz88** [comment]
Thanks for the request again. This is available in 1.1.0 now
