### ISSUE TITLE
Too slow !

### ISSUE THREAD

**Issue by sigma1994** [stepstone-tech/android-material-stepper#180]
i use 3 fragment but it's too slow when launching activity.

**Comment by zawadz88** [comment]
Hi,
Could you provide any metrics to back this up?
What device does this happen on?
Are you not doing anything heavy in the Fragments when creating them?
Does it happen in the sample app?

**Comment by sigma1994** [comment]
These are fragments:
//////////////////////////////////////////////////////////////////////////////////////////////

`public class TimeAndPlaceFragment extends Fragment implements BlockingStep {
    private FragmentTimeAndPlaceBinding binding;
    private FragmentTimeAndPlaceViewModel viewModel;

    public TimeAndPlaceFragment() {
    }

    public static TimeAndPlaceFragment newInstance(String param1, String param2) {
        TimeAndPlaceFragment fragment = new TimeAndPlaceFragment();
        Bundle args = new Bundle();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_time_and_place, container, false);
        return binding.getRoot();
    }

    @Override
    public void onStart() {
        super.onStart();
        viewModel = new FragmentTimeAndPlaceViewModel();

        Observable.fromCallable(ApiManager::getCurrentPersianDate).subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread()).subscribeWith(new Observer<String>() {
            @Override
            public void onSubscribe(Disposable d) {

            }

            @Override
            public void onNext(String response) {
                if (response != null) {
                    PersianDateParser persianDateParser = new PersianDateParser(response);
                    viewModel.currentDate.set(persianDateParser.getPersianDate().getPersianLongDate());
                    viewModel.currentDateReal.set(response);
                    onComplete();
                } else {
                    onError(new Throwable("empty date"));
                }
            }

            @Override
            public void onError(Throwable e) {
                PersianDateParser persianDateParser = new PersianDateParser("1396/5/8");
                viewModel.currentDate.set(persianDateParser.getPersianDate().getPersianLongDate());
                viewModel.currentDateReal.set("1396/5/8");
            }

            @Override
            public void onComplete() {

            }
        });

        RecyclerInitializer recyclerInitializer = new RecyclerInitializer(RecyclerInitializer.VERTICAL, 1, new AddressAdapter(RealmManager.getUserAddresses(), false, true), false, false);

        ArrayList<TimeViewModel> list1 = new ArrayList<>();
        TimeViewModel timeViewModel = new TimeViewModel("09:00 الی 11:00", 0, new RealmTime(9, 0, true), new RealmTime(11, 0, true));
        list1.add(timeViewModel);
        timeViewModel = new TimeViewModel("12:00 الی 13:00", 1, new RealmTime(12, 0, true), new RealmTime(13, 0, true));
        list1.add(timeViewModel);
        RecyclerInitializer recyclerInitializer1 = new RecyclerInitializer(RecyclerInitializer.VERTICAL, 1, new TimeAdapter(list1, getActivity(), viewModel), false, false);
        viewModel.riTime.set(recyclerInitializer1);
        viewModel.riAddress.set(recyclerInitializer);
        binding.setViewModel(viewModel);
        binding.executePendingBindings();

    }

    @Override
    public VerificationError verifyStep() {
        String error = null;

        if (!RealmManager.isLoggedIn()) {
            error = "وارد حساب کاربری خود شوید";
            return new VerificationError(error);
        }
        if (!binding.getViewModel().isSelectedAddress.get()) {
            error = "آدرس انتخاب نشده است";
            return new VerificationError(error);
        }
        if (!binding.getViewModel().isSelectedTime.get()) {
            error = "زمان تحویل را نتخاب کنید";
            return new VerificationError(error);
        }
        return null;
    }

    @Override
    public void onSelected() {
        ((AddressAdapter) binding.getViewModel().riAddress.get().getAdapter()).updateData(RealmManager.getUserAddresses());
    }

    @Override
    public void onError(@NonNull VerificationError error) {
        Toast.makeText(TimeAndPlaceFragment.this.getActivity(), error.getErrorMessage(), Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onNextClicked(StepperLayout.OnNextClickedCallback callback) {
        callback.goToNextStep();
    }

    @Override
    public void onCompleteClicked(StepperLayout.OnCompleteClickedCallback callback) {
    }

    @Override
    public void onBackClicked(StepperLayout.OnBackClickedCallback callback) {
        callback.goToPrevStep();
    }

}
`

`public class CartFragment extends Fragment implements BlockingStep {

    private FragmentCartBinding binding;
    private FragmentCartViewModel viewModel;

    public CartFragment() {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_cart, container, false);
        return binding.getRoot();
    }

    @Override
    public void onStart() {
        super.onStart();
        viewModel = new FragmentCartViewModel();
        RecyclerInitializer recyclerInitializer = new RecyclerInitializer(RecyclerInitializer.VERTICAL, 1, new CartProductsAdapter(RealmManager.getCartProducts(), false, true), false, false);
        recyclerInitializer.setRecyclerView(binding.rvProducts);
        viewModel.recyclerInitializer.set(recyclerInitializer);
        viewModel.init(RealmManager.getRealmCart());
        binding.setViewModel(viewModel);
        binding.executePendingBindings();
    }

    @Override
    public VerificationError verifyStep() {
        if (RealmManager.getRealmCart().getCartSize() == 0) {
            return new VerificationError("سبد خرید خالی است");
        }

        if (!CustomUtils.isConnectedToNetwork(getActivity())) {
            return new VerificationError("دستگاه به اینترنت متصل نیست");
        }
        if (!RealmManager.isLoggedIn()) {
            new Handler(Looper.getMainLooper()).postDelayed(() -> ActivityManager.startActivity(CartFragment.this.getActivity(), LoginActivity.class), 1000);
            return new VerificationError("وارد حساب کاربری خود شوید");
        }
        return null;
    }

    @Override
    public void onSelected() {

    }

    @Override
    public void onError(@NonNull VerificationError error) {
        Toast.makeText(CartFragment.this.getActivity(), error.getErrorMessage(), Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onNextClicked(StepperLayout.OnNextClickedCallback callback) {
        callback.getStepperLayout().showProgress("دریافت اطلاعات جدید از سرور...");
        Observable.fromCallable(ApiManager::getUserAddressData).subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread()).subscribeWith(new Observer<Boolean>() {
            @Override
            public void onSubscribe(Disposable d) {

            }

            @Override
            public void onNext(Boolean aBoolean) {
                if (aBoolean) {
                    callback.getStepperLayout().hideProgress();
                    callback.goToNextStep();
                }
            }

            @Override
            public void onError(Throwable e) {
                callback.getStepperLayout().hideProgress();
            }

            @Override
            public void onComplete() {
                callback.getStepperLayout().hideProgress();
            }
        });
    }

    @Override
    public void onCompleteClicked(StepperLayout.OnCompleteClickedCallback callback) {

    }

    @Override
    public void onBackClicked(StepperLayout.OnBackClickedCallback callback) {

    }

}`
////////////////////////////////////////////////////////////////////////////////////////////////////

i tested it on emulator, Galaxy C5 & C9 and it take too much time to load the activity and this is adapter code :

//////////////////////////////////////////////////////////////////////////////////////////////////

`public class MyStepperAdapter extends AbstractFragmentStepAdapter {
    private final List<Fragment> mFragmentList = new ArrayList<>();
    private final List<StepViewModel> viewModels = new ArrayList<>();

    public MyStepperAdapter(FragmentManager fm, Context context) {
        super(fm, context);
        CartFragment cartFragment = new CartFragment();
        TimeAndPlaceFragment timeAndPlaceFragment = new TimeAndPlaceFragment();
        ConfirmPaymentFragment confirmPaymentFragment = new ConfirmPaymentFragment();
        mFragmentList.add(cartFragment);
        mFragmentList.add(timeAndPlaceFragment);
        mFragmentList.add(confirmPaymentFragment);

        StepViewModel stepViewModel = new StepViewModel.Builder(context).setTitle(R.string.cart).create();
        viewModels.add(stepViewModel);
        stepViewModel = new StepViewModel.Builder(context).setTitle(R.string.timeAndPlace).create();
        viewModels.add(stepViewModel);
        stepViewModel = new StepViewModel.Builder(context).setTitle(R.string.pay_confirm).create();
        viewModels.add(stepViewModel);

    }

    @Override
    public Step createStep(int position) {
        return (Step) mFragmentList.get(position);
    }


    @Override
    public int getCount() {
        return viewModels.size();
    }

    @NonNull
    @Override
    public StepViewModel getViewModel(@IntRange(from = 0) int position) {
        return viewModels.get(position);
    }
}`

**Comment by zawadz88** [comment]
I would suspect the following to be the source of the slowdown:
```
@Override
public void onSelected() {
    ((AddressAdapter) binding.getViewModel().riAddress.get().getAdapter()).updateData(RealmManager.getUserAddresses());
}
```

`onSelected()` gets called on the UI thread when creating the StepperLayout and you're querying Realm for some addresses which is probably time consuming. That's a guess though and I would suggest debugging it more thoroughly e.g. by adding some logs in various methods of your code and/or with systrace: https://youtu.be/9HtTL_RO2wI

This doesn't look like a library bug to me though.

**Comment by sigma1994** [comment]
Thanks.
I solved the issue.
