### ISSUE TITLE
Not a BUG, Direction needed, error fragment/view

### ISSUE THREAD

**Issue by willemevenwel** [stepstone-tech/android-material-stepper#181]
Hi,

Thanks for awesome lib. 

I have a question. A user will follow the stepper wizard to register, a long the process a different route could need to be taken. Maybe if certain option is checked then go to fragment X, otherwize fragment Y.

The instance where i want to use this is when a user does something really wrong or doesnt qualify, take them to a help screen within the stepper (but on last page) to supply more information. This fragment not necessarily included in the initial setup of the stepper.

like this step doesnt exist in public Step createStep(int position) delegate method. But will need to exist if user checks a check box or whatever.

Regards, and thanks for your patience

Willem

Make sure these boxes are checked before submitting your issue - thank you!

- [x] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [x] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

**Comment by zawadz88** [comment]
Hi @willemevenwel,
This seems to be related to #156.
Please let me know if this answers your question.

**Comment by zawadz88** [comment]
Hi @willemevenwel,
Does that answer your question or would like some more help?
