### ISSUE TITLE
What if you rotate while being in "onNextClicked"

### ISSUE THREAD

**Issue by Quentin1010** [stepstone-tech/android-material-stepper#185]
Everything is in the title: what do you do when you rotate the screen while working in onNextClicked method ?

I simply tried with a handler to post delayed by 5 seconds the 'onNextClickedCallback.goToNextStep()' and rotate in those 5 seconds. The callback did get called, but nothing happened.

Did you ever stumble across this, and did you work with it if so ?

**Comment by zawadz88** [comment]
Hi @Quentin1010,
If you have a long-running operation which you start in`BlockingStep#onNextClicked(callback)` then when rotating a device or exiting the screen you should usually cancel that operation.

Alternatively, if it's necessary for the operation to survive the orientation changes you could keep it e.g. as an Activity singleton and after rotating the device check if there is an ongoing operation and if so update the UI accordingly.

If you wish to go the extreme, you could also block orientation changes for the duration of the operation.

**Comment by Quentin1010** [comment]
Thanks for answering!
I don't have enough time to build a solution about keeping states of everything at each rotation.
Since my actions only lasts 4-5 seconds, I think I will just block the orientation.

Just wondering, is it possible to keep the `StepperLayout.OnNextClickedCallback` callback instance to use it after a rotation or is this instance only linked to the now-dead Activity and calling it won't do anything anyway?

**Comment by zawadz88** [comment]
This callback keeps a reference to `StepperLayout` so keeping this would most probably cause memory leaks.

**Comment by Quentin1010** [comment]
Thanks!
