### ISSUE TITLE
Crash with three fragments...

### ISSUE THREAD

**Issue by urbutisj** [stepstone-tech/android-material-stepper#191]
hi, thanks for this lib! 👍 I stuck a little bit, and maybe you will know how to fix it :) So I have 3 Fragments. And I'm taking the adapter in them(Here is the code):
`mStepperLayout = (StepperLayout) view.findViewById(R.id.stepperLayout);

 mStepperLayout.setAdapter(new MyStepperAdapter(getFragmentManager(),getContext()));`

I press button in Activity, and I enter in first fragment, here I start to use this lib  
So when i run my app, and press that button from activity I'm getting an error (Here is the code):
`E/AndroidRuntime: FATAL EXCEPTION: main
Process: app, PID: 1643
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String app.SelectionAdapters.ListItem.getCode()' on a null object reference

at app.Fragments.SelectNewJobListFragment$4$1.run(SelectNewJobListFragment.java:192)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5728)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)`

Here is these lines:
![image](https://user-images.githubusercontent.com/17598495/29714239-f8b2f8c0-89aa-11e7-823e-a8cbee973d9c.png)

Here is this listItems code: 

![image](https://user-images.githubusercontent.com/17598495/29714472-0dbaff96-89ac-11e7-9f18-27ff11a971c9.png)

And if I paste the code like from example here(Only one Fragment) then application not crash:
![image](https://user-images.githubusercontent.com/17598495/29714298-33a714de-89ab-11e7-84f5-59c11b49f8e7.png)

At the final it should work like that : when user press button in the first fragment, he goes in the second, if press button in second - goes in the third and after that he goes in Activity.

I hope you understand my problem. Thanks for any help ;)

**Comment by zawadz88** [comment]
Hi @urbutisj,
It doesn't look like a library error to me TBH.
It seems like `mParentListItem` in your sample is `null` however based on your code it's hard to tell why this is.
In your place, I'd debug this, check if `mParentListItem` is in fact `null` and find where you're setting it.
