### ISSUE TITLE
RFE: Add ability to use swipe gesture to go to next or previous step

### ISSUE THREAD

**Issue by farrukhnajmi** [stepstone-tech/android-material-stepper#194]
The BACK / NEXT button provide the default mechanism to go to the previous / next steps. It would be a usability improvement if a swipe left / right gesture do the same.

**Comment by zawadz88** [comment]
Hi,
This is actually disabled on purpose so that you can only go the next step if it's verified.

**Comment by zawadz88** [comment]
If however you wish to enable this in your app, you would need to remove `onInterceptTouchEvent` and `onTouchEvent` methods from `StepViewPager` and `mPager.setOnTouchListener` from `StepperLayout#init()`.
However, I don't think this is a pattern used by any of the steppers I've seen.
