### ISSUE TITLE
Tabs Labels

### ISSUE THREAD

**Issue by urbutisj** [stepstone-tech/android-material-stepper#195]
Hello, is it possible to move these labels below dots? not side by side :) 
![image](https://user-images.githubusercontent.com/17598495/29761467-d7c8f80c-8bd1-11e7-82a0-ab380dfc6755.png)

**Comment by urbutisj** [comment]
And does it work with Android 5?

**Comment by zawadz88** [comment]
Hi,
This was already requested in #183. Min SDK is 14 so it should :) If you encounter any errors please submit a new issue.

**Comment by urbutisj** [comment]
Thanks for answer @zawadz88  👍
