### ISSUE TITLE
Show tabLayout over Fragment

### ISSUE THREAD

**Issue by guzfernandez** [stepstone-tech/android-material-stepper#198]
Is it possible to show the tab layout over the fragment? 
What I want to achieve is to show the stepper with only dots but over the fragment.
Currently, you can only see the fragment above the stepper layout.

**Comment by zawadz88** [comment]
Hi @guzfernandez,
Would you still like to see the navigation buttons as well? Also, would navigation bar background be partially visible in this scenario? Or are you just interested in the dots?

**Comment by guzfernandez** [comment]
I'm just interested in the dots actually, but seeing the navigation buttons could be optional.
About the bar background, I would like it to be completely transparent.

**Comment by zawadz88** [comment]
Thanks for the info.
So the library doesn't support this. I think that what you're describing is not really an actual stepper and the library probably shouldn't handle this...

There are some other libraries though which create a dotted indicator, e.g. https://github.com/robohorse/pagerbullet so maybe you could use that instead?

**Comment by guzfernandez** [comment]
Yeah, that's what I'm looking for. Thanks!
