### ISSUE TITLE
Is it possible to change the behavior of Android system back softkey

### ISSUE THREAD

**Issue by yccheok** [stepstone-tech/android-material-stepper#20]
Currently, by pressing the Android system back softkey, it will quit the entire wizard activity.

However, is there possibility, that we can change such behavior in the way.

1) If we are in step 2, step 3, ... , pressing Android system back softkey, will enable us to back to page step 1, step 2, ...

2) If we are in step 1, pressing Android system back softkey, will enable us to quit the entire wizard activity.

Thank you

**Comment by zawadz88** [comment]
Hi,
The StepperLayout does not handle presses on the Back button itself. This is actually handled by the Activity/Fragment it is in. In the sample app it is handled by overriding onBackPressed() method: https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/AbstractStepperActivity.java and simply closing the Activity if we are on step 1.
However, this behavior can be changed as you please :) I hope this answers your question.

**Comment by yccheok** [comment]
Opps. Thanks for the great tip. I think that solves my concern. Thanks.

**Comment by chiragmobibox** [comment]
Hi Please give me solution
@yccheok please give me code if your code is work

**Comment by chiragmobibox** [comment]
@zawadz88 
https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/AbstractStepperActivity.java

this link is not working

**Comment by zawadz88** [comment]
Hi,
This class was converted to Kotlin. New link: https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/AbstractStepperActivity.kt
