### ISSUE TITLE
Espresso

### ISSUE THREAD

**Issue by huttneab** [stepstone-tech/android-material-stepper#201]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] Check in the issue tracker whether
      this issue wasn't already reported.
- [x ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [x ] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

What version do we include in our build file for the espresso tests ?

`androidTestCompile "com.stepstone.stepper:espresso-material-stepper:X.X.X" `

 I can't seem to locate a version that gradle will build on (looks like the x.x.x implied the latest, 4.2.0?).

Thanks.

**Comment by RobertZagorski** [comment]
Yes, the version number you provided is the right one.
You can always check the version of library in [material-stepper Bintray site](https://bintray.com/fabian/maven/material-stepper).

**Comment by huttneab** [comment]
@robertherdzik are you sure it's available on Maven?

here's the error I get when building

![image](https://user-images.githubusercontent.com/1134161/30553146-44e37c9e-9c6e-11e7-88ba-02c0e34fd35d.png)

My repository section in my build.gradle
![image](https://user-images.githubusercontent.com/1134161/30553286-c859a472-9c6e-11e7-8855-810c444283c6.png)

**Comment by huttneab** [comment]
adding the following seems to fix the resolution issue
'
    maven {
        url  "https://dl.bintray.com/fabian/maven"
    }
'

**Comment by huttneab** [comment]
update,

use this for your import to avoid conflicts with Espresso (I was not able to use the intents test rule until I excluded espresso test from the dependency).

```
androidTestCompile('com.stepstone.stepper:espresso-material-stepper:4.2.0', {
          exclude group: 'com.android.support.test.espresso'
})
```

**Comment by zawadz88** [comment]
Hi @huttneab,
Which version of Espresso are you using?
The library uses 3.0.0 and you need a Google repository link in your build.gradle to use that.
