### ISSUE TITLE
Remove Next and Back button in progrees bar type

### ISSUE THREAD

**Issue by Sirvanalie** [stepstone-tech/android-material-stepper#206]
I want to remove Back and Next button in progress bar type, but just can remove all of them with progress bar. How I can, use progress bar with match parent width, without any button ? Thanks for reply.

**Comment by RobertZagorski** [comment]
When creating this library, a special care was put on following [Steppers' Material Design guidelines](https://material.io/guidelines/components/steppers.html#steppers-usage). Mobile steps should give the possibility to go back and next.

As far as I understand your request, I'd suggest simply putting `ProgressBar` in your layout and increase it's progress according to your needs.

**Comment by Sirvanalie** [comment]
Thanks 
@RobertZagorski  for reply. I did it, and use ProgressBar in my layout, but I want change any part of ProgressBar. For example when in quiz app, answer is false, first color part of ProgressBar  must be set Red color for it, also when second answer is true,  second color part of ProgressBar  must be set Green color. I can't implement this ProgressBar  . But when I read document of this library , I see I can implement this scenario with this library.

**Comment by zawadz88** [comment]
Hi @Sirvanalie,
Could you reference the documentation, please?
I don't recall the library being able to do that with the progress bar. It can set the error message on a step's tab though, but that's only for the tabbed stepper.

**Comment by Sirvanalie** [comment]
@zawadz88 Thanks bro. I
