### ISSUE TITLE
Tab - inactive tab color

### ISSUE THREAD

**Issue by nibo** [stepstone-tech/android-material-stepper#207]
Hi...
I'd like to use a color with transparency as inactive color for the tabs. 
I haven't found a solution by myself - is this possible?

**Comment by zawadz88** [comment]
Hi @nibo,
This should be theoretically possible by specifying an alpha in the color, e.g.
   
    app:ms_inactiveStepColor="#33ff0000"

however I see that there's some issue where a black background is visible underneath.

I'll investigate and get back to you.

**Comment by nibo** [comment]
Thank's for replay...

**Comment by zawadz88** [comment]
Thanks for the hint.
After changing `mStepIconBackground.setColorFilter(mUnselectedColor)` to `mStepIconBackground.setColorFilter(mUnselectedColor, PorterDuff.Mode.SRC_IN)` it seems to be fixed!
I'll submit a PR shortly.

**Comment by nibo** [comment]
Thats awesome - thank you!

**Comment by zawadz88** [comment]
Fixed, this will be in `4.3.0`. Thanks for reporting this.
