### ISSUE TITLE
change the color of the next button programmatically

### ISSUE THREAD

**Issue by mariaCP** [stepstone-tech/android-material-stepper#209]
Is it possible to change the color of the next button programmatically? Thank your for response.

**Comment by zawadz88** [comment]
Hi,
It's possible via `ms_nextButtonColor`. Please see e.g. the styled tabs layout XML in the sample app.

**Comment by mariaCP** [comment]
Hello, thank you for response, I have seen that it is possibile via XML, I would like to know that it is possibile programmatically.

**Comment by zawadz88** [comment]
Hi @mariaCP 
Sorry, I missed that.
This is not actually possible currently but it was already requested in #132 which is still open.
