### ISSUE TITLE
Separator line above back/next buttons possible?

### ISSUE THREAD

**Issue by Rainer-Lang** [stepstone-tech/android-material-stepper#213]
Is it possible to show a line above to back/next buttons?

I need this because sometimes the keyboard is shown and the buttons are pushed above. It's hard to separate these buttons to the content.
Maybe there is another/better solution than a line...

**Comment by zawadz88** [comment]
Hi @Rainer-Lang,
Could you post a screenshot, please?

You can change the background of the bottom navigation bar via `ms_bottomNavigationBackground` attribute. This background can contain a separator or change the color of the entire bottom navigation bar.

Alternatively, you could add an elevation to the bottom bar by changing the style of the bottom navigation (see https://github.com/stepstone-tech/android-material-stepper#custom-styling). The latter would work on Lollipop+ though.

**Comment by Rainer-Lang** [comment]
@zawadz88 It worked.  I'm using now `elevation`. Thanks.

**Comment by cboisen** [comment]
@Rainer-Lang Sorry to bother you, but can you post your styles regarding the elevation? I'm in a similar position (the stepper should be elevated from the content below).
