### ISSUE TITLE
Error inflating class com.stepstone.stepper.StepperLayout

### ISSUE THREAD

**Issue by zhiephie** [stepstone-tech/android-material-stepper#214]
`Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #222: Error inflating class com.stepstone.stepper.StepperLayout`

What is wrong?

**Comment by zawadz88** [comment]
Hi @zhiephie,
Please post the way you're using StepperLayout in your layout file as well the Build tools and Support library versions you're using in the project.

**Comment by zhiephie** [comment]
Hi, @zawadz88 , Thanks for the reply. 

I explain in here https://gist.github.com/zhiephie/3a92ed37eda93b9963e1630542129d9b

Btw, every time I use `ms_stepperType="tabs"`, display on design always error and android studio lag.

**Comment by zhiephie** [comment]
I found mistake in my code

here `app:ms_stepperLayoutTheme="@style/DotStepperStyle"/>`

Thanks @zawadz88
