### ISSUE TITLE
Blank space and cut EditText on showing keyboard

### ISSUE THREAD

**Issue by fgagneten** [stepstone-tech/android-material-stepper#217]
I implemented: 

<?xml version="1.0" encoding="utf-8"?>

    <com.stepstone.stepper.StepperLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/stepperLayout"
    app:ms_activeStepColor="@color/verdeExito"
    app:ms_backButtonColor="@color/azulOscuro"
    app:ms_completeButtonColor="@color/verdeExito"
    app:ms_nextButtonColor="@color/azulOscuro"
    app:ms_backButtonText="@string/atras"
    app:ms_nextButtonText="@string/siguiente"
    app:ms_completeButtonText="@string/enviar"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:ms_stepperFeedbackType="tabs|content|disabled_bottom_navigation"
    app:ms_stepperType="tabs" />
`

When there are severals EditText (or another objects) and the keyboard is showing, the first part of the layout is below the stepper, and also there are a blank space at the final. 

Could you help me?

Thanks.

**Comment by zawadz88** [comment]
Hi @fgagneten,
Could you share a screenshot, please?

**Comment by fgagneten** [comment]
This is the first view:

![screenshot_20171005-111528](https://user-images.githubusercontent.com/14353978/31232083-1bea95b2-a9bf-11e7-82b9-f0fae67220bd.png)

After you touch in the first edittext, because you want to write something into it: the keyboard opens
![screenshot_20171005-111540](https://user-images.githubusercontent.com/14353978/31232082-1be280fc-a9bf-11e7-92f6-5341cf353388.png)

It shows me editext2, but I need to see what I'm writing in the edittext1, so.. I swipe up to the first edittext but this is the top of the view (I think the first edittext is below the stepper):
![screenshot_20171005-111608](https://user-images.githubusercontent.com/14353978/31232084-1becd2fa-a9bf-11e7-8c8e-c64c74e27ccf.png)

**Comment by zawadz88** [comment]
Hi @fgagneten,
So I've added more `EditText`s in the sample app inside of a `ScrollView`, but couldn't reproduce what you're describing.

Could you please provide a sample app where this could be reproduced?

**Comment by fgagneten** [comment]
I found the problem. It's caused on setting
    `android:layout_gravity="center_vertical"`
in a LinearLayout that contains the EditText.

**Comment by fgagneten** [comment]
The problem removing 

`android:layout_gravity="center_vertical"`

is that you are not able to center edit text or textview.

Any solution for that?
