### ISSUE TITLE
Save the data with 4 step and multi EditText (Question)

### ISSUE THREAD

**Issue by kantot** [stepstone-tech/android-material-stepper#218]
I've read this https://github.com/stepstone-tech/android-material-stepper/issues/15

I'm a newbie on android, and I'm confused to save a lot of data on these 4 steps.

I have EditText Like this

![screenshot from 2017-10-09 15-55-29](https://user-images.githubusercontent.com/5674973/31331409-650b084e-ad0c-11e7-8532-c0672c6426fe.png)

How to reproduce this code for multi save data and get data
```
public interface DataManager {

    void saveData(String data);

    String getData();

}
```
and how to implement it here https://github.com/stepstone-tech/android-material-stepper/blob/v3.2.2/sample/src/main/java/com/stepstone/stepper/sample/PassDataBetweenStepsActivity.java

**Comment by zawadz88** [comment]
Hi @kantot,
Instead of saving a `String` you could use a custom data class (make it `Parcelable` or `Serializable` so that is survives Activity being destroyed) and save it instead. This class could hold all your fields.

**Comment by kantot** [comment]
Hi, thanks. I'll try it.

**Comment by yudikarma** [comment]
hi @kantot you was solving this problem ? i have same problem. please tell me how to do. 

thanks so much
