### ISSUE TITLE
Is there an option to hide error message inside tab?

### ISSUE THREAD

**Issue by Riedi2070** [stepstone-tech/android-material-stepper#219]
Much thanks for the great library!!!

I'am using the stepper with error message inside the tab. Now, I want that hide the error message programtically when user input text in an edittext field.

Is there a option to reset der error message in the tab?

Thanks for your ideas!

**Comment by zawadz88** [comment]
Hi,
Try `StepperLayout#updateErrorState(null)` maybe?

**Comment by Riedi2070** [comment]
Hi,

great thx! `StepperLayout#updateErrorState(null)` works fine!
