### ISSUE TITLE
Caused by: org.xmlpull.v1.XmlPullParserException: invalid drawable tag vector

### ISSUE THREAD

**Issue by sanjayrajsinh** [stepstone-tech/android-material-stepper#220]
<b> This error occur in android version 4.4.2  , This code working proper in  marshmallow and lollipop but  android version 4.4.2 get a error</b>

<br>
<p> build.gradle</p>
<pre> android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId "my.applicationnew"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 1
        versionName "1.0.0"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    aaptOptions {
        cruncherEnabled = false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'nl.psdcompany:duo-navigation-drawer:2.0.6'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    testCompile 'junit:junit:4.12'
}
</pre>

**Comment by zawadz88** [comment]
Hi,
You need to use Support Library `25.4.0` minimum.

**Comment by sanjayrajsinh** [comment]
@zawadz88  why and what a reason?

**Comment by zawadz88** [comment]
@sanjayrajsinh this was a breaking change introduced in `4.0.0`:
https://github.com/stepstone-tech/android-material-stepper/blob/master/CHANGELOG.md

>Updated Android Support Library version to 25.4.0 to support vector animations without a pre-Lollipop fallback (issue #154)

The README file also contains this information: https://github.com/stepstone-tech/android-material-stepper#download-from-jcenter

**Comment by zawadz88** [comment]
Did upgrading to `25.4.0` solve the issue for you?
