### ISSUE TITLE
Add the Spanish translation of string resources

### ISSUE THREAD

**Issue by durey** [stepstone-tech/android-material-stepper#223]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [ ] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

Can I create a pull request with the Spanish translation of string resources? I have it already prepared. Thank you for your time!

**Comment by zawadz88** [comment]
Hi @durey,
Sure! Please go ahead :)
