### ISSUE TITLE
Add listeners when on back & on complete

### ISSUE THREAD

**Issue by durey** [stepstone-tech/android-material-stepper#224]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [ ] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

Can I create a pull request providing callbacks when user clicks on Back & Complete buttons? Quite useful depending on the needs and transparent to current uses. I have the changes already prepared! Thank you for your time!

**Comment by zawadz88** [comment]
Hi @durey,
Thanks for contributing! 
I have a question though - how would that be different from what's described in https://github.com/stepstone-tech/android-material-stepper#making-extra-operations-before-going-to-the-next-step ?

**Comment by durey** [comment]
@zawadz88 Sorry, I see now I didn't explain myself properly (sorry, I am doing a lot of different things at the same time... 😓 ).

What I would like is to emulate the "Continue" click from the Activity, not only from inside the Fragment. That way, all the code defined in the `BlockingStep.onNextClicked` would be executed as if the user would have clicked on "Continue". Can we currently achieve that?

I've tried with `stepperLayout.onNextClickedOut()`, but it doesn't seem to work.

**Comment by zawadz88** [comment]
Hi,
I'm not quite sure what you mean, but I guess it's best to see it if you have the changes already ready.
So please go ahead and submit a PR :)

Thanks

**Comment by durey** [comment]
Mmm, never mind! I solved it in a different way without the need of twerking the library. Sorry for wasting your time here, I close this! Thank you for everything!

**Comment by durey** [comment]
Mmm, never mind! I solved it in a different way without the need of twerking the library. Sorry for wasting your time here, I close this! Thank you for everything!
