### ISSUE TITLE
fragment created before get visible to user.

### ISSUE THREAD

**Issue by mrzslr** [stepstone-tech/android-material-stepper#226]
hi there, I have an issue, I have 3 step fragment in StepAdapter. when the first fragment showed to the user, the next 2 fragment oncreateView called before I see.
what's the problem?

**Comment by zawadz88** [comment]
Hi,
StepperLayout uses a ViewPager internally so it will always create the Fragments/Views next to the currently selected one.

**Comment by zawadz88** [comment]
Hi @mohammadreza,
Were you able to solve your issue?

**Comment by shahimclt** [comment]
@mohammadreza that is the intended behavior as the lib uses a ViewPager internally. If what you want is to run some code only when the step is visible to the user, you can put that code in `StepFragment.onSelected()`. Hope this helps.
