### ISSUE TITLE
Change progress text color after finish the final step

### ISSUE THREAD

**Issue by fgagneten** [stepstone-tech/android-material-stepper#227]
Is there any possibility to change the color of the progress text when you finish the final step? change black to white: 
[Click here](https://github.com/stepstone-tech/android-material-stepper/blob/master/gifs/stepper-feedback.gif)

**Comment by zawadz88** [comment]
Hi,
Do you mean "Operation in progress, please wait..."?
I don't think it's currently supported unfortunately. Could you the scenario in which this would be useful?

**Comment by fgagneten** [comment]
Yes! 
If you choose a dark blue background for the stepper, the text will not constract with the background.

**Comment by zawadz88** [comment]
If this change is to be for all the steps then you achieve that by specififying a custom progress text style with 'ms_stepTabsProgressMessageStyle'. Please see https://github.com/stepstone-tech/android-material-stepper/blob/master/material-stepper/src/main/res/layout/ms_tabs_container.xml and https://github.com/stepstone-tech/android-material-stepper#custom-styling

Please let me know if this solves your issue!

**Comment by zawadz88** [comment]
Hi @fgagneten,
Have you solved your issue?

**Comment by fgagneten** [comment]
Works! 
Finally, I overritten ms_tabs_container.xml
