### ISSUE TITLE
call goToNextStep() in fragment button click listener - question

### ISSUE THREAD

**Issue by mrzslr** [stepstone-tech/android-material-stepper#230]
is there any way to call `goToNextStep() ` in button click listener in the fragment?

fragment onCreateView
```java 
 btnSelect.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
              
              // how can I call goToNextStep() here ?
                
            }
        });
```

**Comment by zawadz88** [comment]
Hi,
Yes, you can do it. Please see the sample: https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/ProceedProgrammaticallyActivity.kt and https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/step/fragment/FormStepFragment.kt

**Comment by mrzslr** [comment]
there is no implements for OnProceedListener in StepperLayout.

**Comment by zawadz88** [comment]
Hi @mohammadreza,
`OnProceedListener` is actually an interface defined in the sample app and implemented by https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/ProceedProgrammaticallyActivity.kt in the sample app.

**Comment by mohammadreza** [comment]
I didn't use Kotlin yet. if it's possible to put the `FormStepFragment.java` I'll be thank you.
