### ISSUE TITLE
Sample apk is corrupt.

### ISSUE THREAD

**Issue by SahajRana** [stepstone-tech/android-material-stepper#231]
The sample app on install shows that it is corrupt 
![screenshot_2017-12-24-02-30-23-213_com google android packageinstaller](https://user-images.githubusercontent.com/16938202/34322629-964eafe2-e852-11e7-8305-aded9f1b5292.png)

**Comment by zawadz88** [comment]
Hi @SahajRana,
Could you provide some steps to reproduce? I cannot really reproduce this locally.
How exactly are installing the app? What device is this happening on, etc.?
