### ISSUE TITLE
invoke within a fragmet onNextClicked ?

### ISSUE THREAD

**Issue by aymenhs** [stepstone-tech/android-material-stepper#233]
I check some answers but didn't find how to invoke from a Fragment the onNextClicked if a user make a selection for example. No need that he pushed the button next . Is it possible?

my fragment:
public class OneFragmentCreation extends Fragment implements BlockingStep { ...

=>>> for the stepper to go to next step

 @Override
    public void onNextClicked(final StepperLayout.OnNextClickedCallback callback) { ...}
}

thanks

**Comment by zawadz88** [comment]
Hi @aymenhs,
It is possible. Please see the Fragment https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/step/fragment/FormStepFragment.kt and the containing Activity https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/ProceedProgrammaticallyActivity.kt
There is a method in StepperLayout called proceed() which you can use.

**Comment by aymenhs** [comment]
thank you very much it works fine !
