### ISSUE TITLE
Step Color

### ISSUE THREAD

**Issue by LucasPoingt** [stepstone-tech/android-material-stepper#234]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] Check in the issue tracker whether
      this issue wasn't already reported.
- [x] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [ ] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

**Comment by LucasPoingt** [comment]
Hi, is there a way to color all the steps with different color ? I need to make a verification to see if all the field of a step are complete, and I would like to prevent the user that a step isn't verified without blocking the progress of the steps. Thank you.

**Comment by zawadz88** [comment]
Hi @LucasPoingt,
I don't think it's possible. Please see https://github.com/stepstone-tech/android-material-stepper/issues/84
