### ISSUE TITLE
onCompleted(completeButton: View?) not working

### ISSUE THREAD

**Issue by JonathanImperato** [stepstone-tech/android-material-stepper#239]
I need to perform some action once i reach the complete button of the last steppers. But when i click on the complete button nothing happen.
I have implemented the StepperLayout.StepperListener and performing my action in that method.
I also tried to add a click Listener to the complete button without results.
Could you explain me what's wrong?
`    override fun onCompleted(completeButton: View?) {  
        this@LaunchActivity.startActivity(myIntent)
        Toast.makeText(this, "done", Toast.LENGTH_LONG).show() 
    }`
my oncreate
```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_launch)
        setSupportActionBar(toolbar2)

        mStepperLayout = findViewById(R.id.stepperLayout) as StepperLayout
        mStepperLayout!!.setAdapter(MyStepAdapter(supportFragmentManager, this))
 
    }
```

**Comment by zawadz88** [comment]
Hi @JonathanImperato,
Could you provide more samples, please? You said you're implementing `StepperLayout.StepperListener` yet in the sample code you provide I cannot really see this :/

**Comment by JonathanImperato** [comment]
`class LaunchActivity : AppCompatActivity(), StepperLayout.StepperListener {

    private var mStepperLayout: StepperLayout? = null


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_launch)
        setSupportActionBar(toolbar2)
        getSupportActionBar()!!.setDisplayHomeAsUpEnabled(true)
        getSupportActionBar()!!.setDisplayShowHomeEnabled(true)

        mStepperLayout = findViewById(R.id.stepperLayout) as StepperLayout
        mStepperLayout!!.setAdapter(MyStepAdapter(supportFragmentManager, this))

        //val mSearchView = findViewById(R.id.searchView) as km.lmy.searchview.SearchView
        /*
        val allergie = arrayOf("Sugar-Conscious", "Peanut-Free", "Tree-Nut-Free", "Alcohol-Free", "Gluten-Free")
        val nachoTextView = findViewById(R.id.nacho_text_view) as NachoTextView
        val adapter = ArrayAdapter(this, android.R.layout.simple_dropdown_item_1line, allergie)
        nachoTextView.setAdapter(adapter)*/
    }
/*
    override fun onCreateOptionsMenu(menu: Menu): Boolean {
        val inflater = menuInflater
        inflater.inflate(R.menu.launch_menu, menu)
        return true
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        val mSearchView = findViewById(R.id.searchView) as km.lmy.searchview.SearchView
        when (item.getItemId()) {
            R.id.search_action -> {
                mSearchView.open()// enable or disable animation
                return true
            }
            else -> return super.onOptionsItemSelected(item)
        }
    }*/

    override fun onCompleted(completeButton: View) {
        Toast.makeText(this, "onCompleted!", Toast.LENGTH_SHORT).show()
    }

    override fun onStepSelected(newStepPosition: Int) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun onError(verificationError: VerificationError?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun onReturn() {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.

    }

}`

**Comment by zawadz88** [comment]
Hi,
I believe you still need to set the listener via `StepperLayout#setListener(listener)`. See https://github.com/stepstone-tech/android-material-stepper/blob/master/README.md#add-a-stepperlistener-in-the-activity-optional

**Comment by JonathanImperato** [comment]
Douh!
Sorry for the waste of time.
