### ISSUE TITLE
RecycleView recreating

### ISSUE THREAD

**Issue by russofinn** [stepstone-tech/android-material-stepper#240]
I use 5 fragments, in the first fragment I have a list with radiobutton, when I select the radiobutton and when I go to the next following the steps, then when I decide to go back to the first fragment the list was created again. Can someone help me?

**Comment by zawadz88** [comment]
Hi @russofinn,
Please see #29

**Comment by russofinn** [comment]
Thank you! I used the ``` mViewPager.setOffScreenPageLimit (int) ``` method and it worked!
