### ISSUE TITLE
How to change the height of Bottom Navigation Bar

### ISSUE THREAD

**Issue by Sutheres** [stepstone-tech/android-material-stepper#243]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [x] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

Is there anyway to change the height of the bottom navigation bar and resize the text on the "Next" and "Back" buttons?

**Comment by zawadz88** [comment]
Hi @Sutheres,
You can do that by setting a custom style on the view as described here: https://github.com/stepstone-tech/android-material-stepper#custom-styling
So you would need to override the style of the navigation bar to change its height and button styles to change font sizes.

**Comment by Sutheres** [comment]
@zawadz88 Thanks! I was able to change the height of the navigation bar and the size of the text. However, I am having trouble trying to override the size of the chevron in the next button. Is there an attribute in ms_nextNavigationButtonStyle that would allow me to use a drawable of my own or of a different size?

**Comment by zawadz88** [comment]
You could change the drawable by specifying a different drawable in the adaper as described here: https://github.com/stepstone-tech/android-material-stepper/blob/master/README.md#changing-button-labels--compound-drawables-per-step

**Comment by hebafouad777** [comment]
@Sutheres  can you tell how did you change the height of navigation bar and the size of the text??
