### ISSUE TITLE
Error inflating class com.stepstone.stepper.internal.widget.StepTab

### ISSUE THREAD

**Issue by BigGitWorld** [stepstone-tech/android-material-stepper#244]
I am using version 3.2.0 and works perfectly.
Now I am going to use version 4.3.1, but the same configuration will result in the following error : 
`Caused by: android.view.InflateException: Binary XML file line #3: Error inflating class com.stepstone.stepper.internal.widget.StepTab`

I am using support library version "26.0.0-alpha1".
what is the problem?

**Comment by zawadz88** [comment]
Hi,
Could you provide more details i.e. Android Gradle Plugin version, target SDK, build tools etc?
Also, there's a stable version of the support lib so not sure if using 26 alpha is the best option currently.

**Comment by zawadz88** [comment]
Hi @BigGitWorld,
Please see the comment above.
Thanks!
