### ISSUE TITLE
StepperLayout with wrap_content height [improvement]

### ISSUE THREAD

**Issue by BigGitWorld** [stepstone-tech/android-material-stepper#245]
I am using this library very well in activities with layout_height=match_parent.
Now I'm going to use it in a DialogFragment with layout_height=wrap_content but does not work.
I want to use wrap_content because my content is little and full screen is not good in UI.
please add this feature to the library too.
thanks

**Comment by zawadz88** [comment]
Hi @BigGitWorld,
How would that work exactly? 
What if the steps used inside have different heights? Should the size of the entire `StepperLayout` change when changing the current step?

Maybe you could use a fixed height instead of `wrap_content`?

**Comment by zawadz88** [comment]
Hi @BigGitWorld,
Please see the question above :)
