### ISSUE TITLE
onCompleted() and onBackClicked() not called

### ISSUE THREAD

**Issue by droid-wise** [stepstone-tech/android-material-stepper#247]
Hey! Thank you for this great library. I have a big problem and i'm not sure if this is my fault or maybe library bug. Maybe I can't use some things together, I have tried everything, but couldn't make this to work.

`onComplete()` not called and `onBackClicked()` also.

Here is my sample:

`public class CreateFieldActivity extends AppCompatActivity implements StepperLayout.StepperListener {

    @BindView(R.id.stepperLayout)
    StepperLayout mStepperLayout;

    private static final String CURRENT_STEP_POSITION_KEY = "current_step_position";

    private static String[] titles = {"Opšte Informacije", "Radno Vreme", "Cena"};

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_create_field);
        ButterKnife.bind(this);

        mStepperLayout.setListener(this);
        mStepperLayout.setAdapter(new MyStepperAdapter(getSupportFragmentManager(), this));
    }

    @Override
    public void onCompleted(View completeButton) {
        Toast.makeText(this, "onCompleted!", Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onError(VerificationError verificationError) {
        Toast.makeText(this, "onError! -> " + verificationError.getErrorMessage(), Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onStepSelected(int newStepPosition) {
        Toast.makeText(this, "onStepSelected! -> " + newStepPosition, Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onReturn() {
        finish();
    }

    public static class MyStepperAdapter extends AbstractFragmentStepAdapter {

        MyStepperAdapter(FragmentManager fm, Context context) {
            super(fm, context);
        }

        @Override
        public Step createStep(int position) {
            final StepFragmentSample step = new StepFragmentSample();
            Bundle b = new Bundle();
            b.putInt(CURRENT_STEP_POSITION_KEY, position);
            step.setArguments(b);
            return step;
        }

        @Override
        public int getCount() {
            return 3;
        }

        @NonNull
        @Override
        public StepViewModel getViewModel(@IntRange(from = 0) int position) {
            //Override this method to set Step title for the Tabs, not necessary for other stepper types
            return new StepViewModel.Builder(context)
                    .setTitle(titles[position]) //can be a CharSequence instead
                    .create();
        }
    }

    /**************** STEP FRAGMENTS ******************/
    public static class StepFragmentSample extends Fragment implements Step {

        @Override
        public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
            //initialize your UI
            View view;
            Bundle args = getArguments();
            if (args.getInt(CURRENT_STEP_POSITION_KEY) == 0) {
                view = inflater.inflate(R.layout.fragment_add_field_step_1, container, false);
            } else if (args.getInt(CURRENT_STEP_POSITION_KEY) == 1) {
                view = inflater.inflate(R.layout.fragment_add_field_step_2, container, false);
            } else {
                view = inflater.inflate(R.layout.fragment_add_field_step_3, container, false);
            }
            return view;
        }

        @Override
        public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
            super.onViewCreated(view, savedInstanceState);

        }

        @Override
        public VerificationError verifyStep() {
            //return null if the user can go to the next step, create a new VerificationError instance otherwise
            return null;
        }

        @Override
        public void onSelected() {
            //update UI when selected
            int currentStepPosition = getArguments().getInt(CURRENT_STEP_POSITION_KEY);

        }

        @Override
        public void onError(@NonNull VerificationError error) {
            //handle error inside of the fragment, e.g. show error on EditText
        }
    }
}`

**Comment by zawadz88** [comment]
Hi,
Are you referring to `onCompleted()` and `onReturn()` from the listener? If so, when are you expecting to receive these callbacks?
