### ISSUE TITLE
Is there a way to enable/ disable back button click operation

### ISSUE THREAD

**Issue by yccheok** [stepstone-tech/android-material-stepper#25]
Currently, by pressing COMPLETE button, I'm going to launch a async task, to perform a long running operation. During that time, I would like to prevent user from clicking the back button. Is there any way to disable back button click operation, programmatically?

Thank.
Cheok

**Comment by fabiozo** [comment]
Hi Cheok

You can control BACK button from you activity/fragment (http://stackoverflow.com/questions/17738966/how-to-disable-back-button-pressed-in-android-fragment-class), nevertheless it is **NOT** recommended from UX perspective. Users always has a possibility to exit you long running operation by tapping on home button for instance.

**Comment by yccheok** [comment]
@fabiozo 

Sorry for doesn't state my question well. I'm not referring the BACK button in Android system soft-key. I'm referring the BACK button in stepper layout.

Currently, pressing the BACK button in stepper layout will always go back to N-1 step fragment. Not sure whether it is possible to disable/ enable such behaviour?

**Comment by fabiozo** [comment]
Hi @yccheok 

Enhancement you requested was added in version 1.1.1. Please have a look at DelayedTransitionStepFragmentSample.java in sample or updated Reademe file:

https://github.com/stepstone-tech/android-material-stepper#make-an-io-operation-before-going-to-the-next-step-optional

Let us know it satisfies your needs.

**Comment by shekharartemedia** [comment]
is there any way to disable android home button programmatically? Thanks in advance.
