### ISSUE TITLE
Help required: How to collect the data of all stepper fragments in last fragment to push on server?

### ISSUE THREAD

**Issue by chnouman** [stepstone-tech/android-material-stepper#251]

**Comment by GuillaumeEbert** [comment]
I use the ViewModel component.  (doc [https://developer.android.com/topic/libraries/architecture/viewmodel.html](url)

Put all your data object in the viewHolder
In each fragement register the ViewModel to the parent activity like this 
`ViewModelProviders.of(getActivity()).get(ClassOfTheViewHolder.class);`

On the on select method get your data from the viewHolder from a getter and Voila your data can be shared between fragments. Just remind you that the ViewHolder is link to the activity life cycle. 

Good codding

**Comment by chnouman** [comment]
@GuillaumeEbert  the link to docs is not found can you please share your working example with just two fragments?

**Comment by felislynx-silae** [comment]
@chnouman [URL](https://developer.android.com/topic/libraries/architecture/viewmodel) if you use architecture components it will work like charm
