### ISSUE TITLE
Disable click from tab on previous step in case it was validated !

### ISSUE THREAD

**Issue by samybeng** [stepstone-tech/android-material-stepper#253]
Hello,

First of all thanks for the lib it really great. 

I just want to know if you can add a feature that will allow us to block a click on a previous validated step from the tab bar.

Make sure these boxes are checked before submitting your issue - thank you!

- [x] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [x] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

**Comment by zawadz88** [comment]
Hi @samybeng,
You can disable clicks altogether but cannot really disable it on individual tabs.
However, I'm not sure if that's a good idea in the first place as the user can always go back by clicking Back in the bottom stepper navigation or simply click the system Back button.
