### ISSUE TITLE
Set the height of the bottom navigation view

### ISSUE THREAD

**Issue by Ruben2112** [stepstone-tech/android-material-stepper#254]
Hey there,

Great library, looks very promising. However, it would be very nice if it would be possible to change the height of the bottom navigation view. Currently when using tablets, it appears to be too small in my opinion.

**Comment by zawadz88** [comment]
Hi @Ruben2112,
This is actually possible to do with the current version of the library.
https://github.com/stepstone-tech/android-material-stepper#custom-styling
Please see the sample app where there's an example:
https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/res/values/styles.xml
`DarkCustomStepperLayoutTheme `

**Comment by Ruben2112** [comment]
I'm sorry, I completely missed that, works great! Thanks!
