### ISSUE TITLE
Is possible to change the VerificationError alertDialog title?

### ISSUE THREAD

**Issue by LuisVargasVic** [stepstone-tech/android-material-stepper#255]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [ ] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

**Comment by zawadz88** [comment]
Hi,
Could you provide a screenshot of the label you would like to change? It would help a lot as I don't quite get the `alertDialog` part TBH.
Thanks!

**Comment by zawadz88** [comment]
Hi @VenkonProgram,
Could have a look at the above, please?
