### ISSUE TITLE
Custom font for StepperLayout tab title

### ISSUE THREAD

**Issue by adiga-maf** [stepstone-tech/android-material-stepper#28]
Is there any way to set custom `TypeFace` for `StepperLayout`'s tab title?

I have tried this way:

`mStepperlayout.setAdapter(new CustomStepperAdapter(getChildFragmentManager()));`
`TextView mStepTitle = (TextView) mStepperLayout.findViewById(R.id.ms_stepTitle);`
`Typeface mFont = Typeface.createFromAsset(getActivity().getAssets(), "CustomFont.ttf");`
`mStepTitle.setTypeface(mFont);`

This works for navigation bar buttons but does not work tab titles, any idea?

**Comment by zawadz88** [comment]
Hi, there is no way currently maybe apart from iterating through view hierarchy and finding all the tab titles but it's a rather nasty solution :/ for this to work it's probably best if we expose the styles for some of the components so that they can be modified.
For the time being you might want to copy the library as a module to your project and use custom fonts inside the library files directly.

**Comment by adiga-maf** [comment]
Can't I override your xml files in my project and set custom font.
For example, let's say that your layout name is: "tab_title" and it contains a `TextView`:
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/tab_title_layout"
    android:layout_width="match_parent"
    android:background="?android:attr/selectableItemBackground"
    android:layout_height="@dimen/default_padding_48"
    android:orientation="vertical">

    <TextView
        android:id="@+id/tab_title_text_view"
        android:layout_width="match_parent"
        android:layout_height="@dimen/default_padding_48"
        android:gravity="end|center_vertical"
        android:paddingEnd="@dimen/default_padding_16"
        android:paddingLeft="@dimen/default_padding_16"
        android:paddingRight="@dimen/default_padding_16"
        android:paddingStart="@dimen/default_padding_16"
        android:textColor="@color/red"
        android:textSize="@dimen/font_size_small" />

</LinearLayout>
`

Can I make the same file name in my layouts folder and modify it like this:
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/tab_title_layout"
    android:layout_width="match_parent"
    android:background="?android:attr/selectableItemBackground"
    android:layout_height="@dimen/default_padding_48"
    android:orientation="vertical">

    <com.mycompany.ui.widgets.CustomTextView
        android:id="@+id/tab_title_text_view"
        android:layout_width="match_parent"
        android:layout_height="@dimen/default_padding_48"
        android:gravity="end|center_vertical"
        android:paddingEnd="@dimen/default_padding_16"
        android:paddingLeft="@dimen/default_padding_16"
        android:paddingRight="@dimen/default_padding_16"
        android:paddingStart="@dimen/default_padding_16"
        android:textColor="@color/_red"
        android:textSize="@dimen/font_size_small" />

</LinearLayout>
`
consider keeping same `TextView` id, but customize it, would this be possible ?

**Comment by zawadz88** [comment]
Hi, you would need to change the layout files directly in the library and put the AAR with the library in your project directly. You could set the font via XML attribute as well with a library such as Calligraphy then.

**Comment by adiga-maf** [comment]
Currently, importing this project as library module isn't possible. However, I am trying to set custom font for `StepperLayout`'s components either by iterating on them or via xml. If there is any possible way to do this, you may help me with it.

Thanks a lot

**Comment by zawadz88** [comment]
Hi, why is it not possible? You could change library in two ways:
1. Copy the library module directly to your project, change build.gradle so that it works with your project's setup and modify the layouts according to your needs.
2. Clone this repo from github on your workstation, modify the layouts to your needs, build the library and use the AAR file as a direct dependenxy instead of the Maven dependency from JCenter.
Have you tried this?

**Comment by adiga-maf** [comment]
Hi @zawadz88 , thanks a bunch for replying back.
I am not experienced with the 2nd step, could you please tell how to do this?

Again, appreciate your reply

**Comment by zawadz88** [comment]
Hi @adiga-maf ,
1. git clone https://github.com/stepstone-tech/android-material-stepper
2. Modify the layouts to your needs
3. ./gradlew assembleRelease
4. Get the AAR file from the _build_ folder
5. Add in the project as described here: http://stackoverflow.com/questions/24506648/adding-local-aar-files-to-gradle-build-using-flatdirs-is-not-working

**Comment by zawadz88** [comment]
Done in #49 and released in 2.2.0. Please see the 'Custom StepperLayout theme' sample for an example of how to do that.
