### ISSUE TITLE
How to remove numbers from tabs?

### ISSUE THREAD

**Issue by Tarcisiofl** [stepstone-tech/android-material-stepper#281]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] Check in the issue tracker whether
      this issue wasn't already reported.
- [ ] If it's a bug report check that clear **steps to reproduce**,
**stacktrace**, **expected behaviour** and other needed details are provided.
- [X] Feature requests contain a **description** of the feature
you're requesting as well as a brief **scenario** explaining
under what circumstances this might be useful.

I'm trying to customize the Tabs to show just the title and change the divider orientation to vertical.
Is it possible?

**Comment by zawadz88** [comment]
Hi,
I think you would need to fork the library and make these changes as it's not supported AFAIK.
