### ISSUE TITLE
Abstract even more the Adapter

### ISSUE THREAD

**Issue by leonardo2204** [stepstone-tech/android-material-stepper#34]
Hey guys, first of all, nice work ! Just found the lib and it seems pretty cool !
Since today a lot of devs (including  me) are moving away from Frags to View-based Apps, I think it would be cool to abstract even more the StepAdapter, so people like me could still use the lib, implementing the abstract Adapter methods, not obligatory using Frags.
I'd be happy to drop a PR, if you guys are interested !

Thanks

**Comment by zawadz88** [comment]
Hi,
That seems like a nice enhancement. We'll gladly review your PR :)

**Comment by leonardo2204** [comment]
@zawadz88 Thanks for the quick reply !
Just a few points:
I was thinking about just abstracting away the findStep and createStep methods.
And also the generics would inherit only from Step, not Fragment.
The class would inherit from PagerAdapter.

How does that sound ? Also, how should we name it ?

Thanks

**Comment by zawadz88** [comment]
@leonardo2204 I think that ideally we would want to have both options i.e. to be able to use a fragment adapter since a lot of people are using it this way and we don't want to take that away from them + a simpler version using views. 
Therefore I think we might want to create some sort of an interface for the step adapter with createStep, findStep & getNextButtonText methods and create two implementations - one inheriting from FragmentPagerAdapter as it is now and a second one inheriting directly from PagerAdapter.
What do you think?

**Comment by leonardo2204** [comment]
Sounds like a plan !
I'll see if I can come up with something until the end of the day !

Thanks

**Comment by leonardo2204** [comment]
I'm just implementing it and I was wondering if passing ViewPager as a parameter to findStep is really necessary.
IMHO, it seems more logical to pass a long (or int) named id.
Using the lib I usually create internal ids.

I'll drop the PR with the ViewPager version because this would be a breaking change, which is not the point of this enhancement.

Thanks :)

**Comment by leonardo2204** [comment]
I've stumbled upon something when implementing the feature.
I created the interface and throughout the code, I realized you were passing the `AbstractStepAdapter`. So, to change, I was passing the Interface. 
Here comes the problem:

```Java
public void setAdapter(@NonNull StepAdapter stepAdapter) {
        this.mStepAdapter = stepAdapter;
        mPager.setAdapter(stepAdapter);

        mStepperType.onNewAdapter(stepAdapter);

        // this is so that the fragments in the adapter can be created BEFORE the onUpdate() method call
        new Handler().post(new Runnable() {
            @Override
            public void run() {
                onUpdate(mCurrentStepPosition);
            }
        });

    }
```

So, as Java doesn't allow multiple inheritance, how should I proceed now ?

Thanks
