### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/widget/TintManager;

### ISSUE THREAD

**Issue by peejay06** [stepstone-tech/android-material-stepper#36]
I had this error after importing stepper to my project. I'm a beginner in android that's why I don't know how to fix this one.

**Comment by zawadz88** [comment]
Hi, could share some of your setup i.e. Android support version, gradle &  gradle Android plugin version, build tools etc? Are you using ProGuard?

**Comment by zawadz88** [comment]
Are you using the same support library version as in the library?

**Comment by zawadz88** [comment]
I couldn't reproduce this with the data I had, therefore closing the issue.
