### ISSUE TITLE
More than 3 Fragment recreate Fragment Created

### ISSUE THREAD

**Issue by RaghuManickam** [stepstone-tech/android-material-stepper#40]
Hi @zawadz88  

I had a issue while adding more than 3 fragments. the first fragment automatically recreates.

With this the data will not be stable in the first fragment as the view is recreated

So i pulled your code and added a line in to your code in setAdapter method

mPager.setOffscreenPageLimit(stepAdapter.getCount());

**Comment by zawadz88** [comment]
Hi @RaghuManickam, 
Could you please provide steps to reproduce?
Did that happen when you got to the third fragment and then back to the first one?
If so, that's actually the desired behaviour you get when using a ViewPager. If you don't want to lose that data you save it in onSaveInstanceState and use it later when the fragment gets recreated.
Setting the offscreen limit solves the issue only partially as it does not handle device rotations, system killing the app in the background, etc.
Please tell me if that's issue.

**Comment by RaghuManickam** [comment]
Hi @zawadz88 ,

this is not an issue this can be done as enhancement.

using saved instance will make more code. if we add this line in the setAdapter method we can resolve this easily.

the user may also review back in that case we need to get data from saved instance .

**Comment by zawadz88** [comment]
Hi @RaghuManickam,
I see your point. Using saved instance state makes more code however it is still needed if you want to make sure your data does not get lost e.g. on rotation, system killing the app or screen resizing in Nougat's multiwindow. 
Increasing the offscreen limit will make the pager keep all the fragments in memory. In case the number of steps is larger this could have a negative impact on the app.
Having said that, I'm thinking about exposing the setOffscreenLimit in a future release. I would not want it to keep all the fragments by default.

**Comment by zawadz88** [comment]
Added in 2.0.0
