### ISSUE TITLE
setting step name from String variables and not resources

### ISSUE THREAD

**Issue by mahermeg17** [stepstone-tech/android-material-stepper#41]
Hi,

any way to set the step name by some strings and not from the resources.
I need to set step name dynamically from strings consumed by a rest api.

Thanks in advance,

**Comment by zawadz88** [comment]
Hi,
Currently this is not possible. I'm thinking about moving some of the stuff from Step to StepAdapter and I could expose it then. I cannot really give you a date when this will happen though.
For the time being you could clone the library and change the return type of getName() in Step to a CharSequence + propagate that change to TabsStepperType and TabsContainer

**Comment by zawadz88** [comment]
Added in 2.0.0. Please see the updated documentation
