### ISSUE TITLE
Jump one step conditionally

### ISSUE THREAD

**Issue by radiolondra** [stepstone-tech/android-material-stepper#47]
Hi,
just a question, not an issue (and maybe a stupid question...).

Lets say in a wizard I have to show 3 steps (1st, 2nd and 3rd) and at runtime I want conditionally jump the 2nd step (so that the user will see the 1st and 3rd steps only). 

For example... The 2nd step is where, in a wizard, we ask for app's permissions or something similar.

Scenario 1:
The user already set all permissions in a previous wizard session. He runs the wizard again. The 2nd step should not be shown at all.

Scenario 2:
 The first time the wizard runs, all 3 steps are shown. In the 2nd step the user allows all  permissions. Then he goes to the 3rd step and clicks "Back"... the 2nd step should be not shown at all (all permissions were already set).

How can I do this?
Many thanks

**Comment by seasox** [comment]
If you would like to skip the step (i.e. it is still shown, but you jump from step 1 to step 3), you might want to use stepperLayout.setCurrentStepPosition after completing step 1. If you want to hide the step entirely (i.e. your Stepper becomes a 2-step layout), take a look at #39.

**Comment by zawadz88** [comment]
Hi,
Regarding the first question - I guess that if you know before showing the stepper how many steps there should be then you could create a different adapter with only 2 steps? In our app we had a similar scenario so we created an adapter factory which created two similar adapters based on some input with different step count.

Regarding the second question - I am not sure if hiding the step with permissions is the best option here. This might be confusing for the user. Imagine this scenario:
1. We show him the permissions step so he sees he's on the second step out of three (either he sees 3 tabs, 3 dots or a progress bar). 
2. He grants the permissions and goes to the third step.
What happens after this? Should he see that there are two steps now? We leave all three steps which allows him to e.g. select the second step by clicking on a tab but tapping Back would change the position to the first step? Either one of these seems to me like bad user experience TBH :/

What I would suggest is leaving all 3 steps after the permissions were granted. When the user wants to go back to the previous step we simply show a screen saying that the permissions were already granted on the second step.

What do you think?

**Comment by radiolondra** [comment]
Hi,

thank you so much for your answers.
And.. Yes, you are right for all the scenarios.

Many many thanks
