### ISSUE TITLE
Not able to change toolbar title/subtitle

### ISSUE THREAD

**Issue by sam4444** [stepstone-tech/android-material-stepper#51]
@zawadz88 Your library is very useful i like it can you please enhance one feature to set toolbar title and subtitle according to active fragment. If this feature already available on your library than can you please guide me how i use that?

**Comment by zawadz88** [comment]
Hi @sam4444,
You can do that by setting a listener in StepperLayout as in
https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/AbstractStepperActivity.java
And changing the title/subtitle of the toolbar in

    public void onStepSelected(int newStepPosition) {//...}

by getting the current step info from the adapter

**Comment by sam4444** [comment]
@zawadz88 thanks for reply i have done this after carefully see all override methods of fragment.
onSelected() method done this.
