### ISSUE TITLE
Functionality question

### ISSUE THREAD

**Issue by Ceaggar** [stepstone-tech/android-material-stepper#53]
It is possible to take the "next button" or trigger the "onNextClicked" method programmatically?
--
Sorry for my English, Thanks so much for this awesome library

**Comment by zawadz88** [comment]
Hi @Ceaggar ,
Could you please describe the problem you are trying to solve? The _onNext()_ method in _StepperLayout_ is currently private, but if there is a scenario where this might be helpful to expose such a method we could add it ;)

**Comment by Ceaggar** [comment]
My problem is quite simple, I need to fill an EditText and when I press "DONE" on the keyboard, I need to move on to the next step immediately.
Currently this is what I do to recreate a scenario similar to `onNextClicked (StepperLayout.OnNextClickedCallback callback)` :

    @Override
    public boolean onEditorAction(TextView textView, int actionId, KeyEvent keyEvent) {
        if (actionId == EditorInfo.IME_ACTION_DONE) {
            VerificationError error = verifyStep();
            if (error == null) {
                onNextClicked(null);
            } else {
                onError(error);
            }
            return true;
        }
        return false;
    }

All this is inside a class that implements `BlockingStep` , of course I have the problem of advancing to the next step using the "stepperLayout", but I solve it with `stepperLayout.setCurrentStepPosition(stepperLayout.getCurrentStepPosition() + 1);`

What I mean is that I have solved my problem, but I think there must be a much cleaner way of doing the same using the convenient methods that the library already has.

In addition to all this, I also have the problem of knowing when the "ms_completeButton" button has been pressed, so that I can execute another 'x' action, such as going to another activity.
What I actually do is that I use the verifyStep () method, because for some reason it is called even when you press "ms_completeButton"

> Thanks so much for the attention paid and for contributing to the community with this excellent library, and sorry for my English again.

**Comment by zawadz88** [comment]
Hi @Ceaggar,
Thanks for the explanation and the feedback!
Regarding:
> stepperLayout.setCurrentStepPosition(stepperLayout.getCurrentStepPosition() + 1);

With the current version of the library that's the way to go.

I agree that there probably should be an API to do that. We'll add it in the next release.

Regarding:
> In addition to all this, I also have the problem of knowing when the "ms_completeButton" button has been pressed, so that I can execute another 'x' action, such as going to another activity.
What I actually do is that I use the verifyStep () method, because for some reason it is called even when you press "ms_completeButton"

You could use StepperLayout.StepperListener which has _void onCompleted(View completeButton)_ method

**Comment by zawadz88** [comment]
Hi @Ceaggar,
This was added in v2.3.0. Please see "Proceed programmatically" in the sample app.

**Comment by Ceaggar** [comment]
Thanks so much! I really appreciate your good work.
