### ISSUE TITLE
Change icons for back/nextButton

### ISSUE THREAD

**Issue by Arkezis** [stepstone-tech/android-material-stepper#54]
Hello,

First of all, thanks for your awesome library ! 
We are using it to provide a nice register flow for our users.

Is it possible to add the possibility to change icons for next/back button thanks to getViewModel(...) in the adapter ? 
It could help us to let the user understand more precisely what he is going (sometimes, text isn't enough ;) )

Thanks a lot,

Tom

**Comment by zawadz88** [comment]
Hi @Arkezis,
Thanks for the feedback!
Just to be clear - you would like to be able to set different icons for each step?

**Comment by Arkezis** [comment]
hi @zawadz88, 

That's exactly what we want :)

**Comment by zawadz88** [comment]
Hi @Arkezis,
This was added in v2.3.0. Please see "Custom navigation buttons" in the sample app :)

**Comment by Arkezis** [comment]
Perfect, it works very well :)

Thanks a lot !
