### ISSUE TITLE
Remove Arrow

### ISSUE THREAD

**Issue by sdejesusF** [stepstone-tech/android-material-stepper#55]
Hi, 
I tried to find where I can remove the arrow icon from the options but I didn't find it. I read in another issue that it has that option.

I want to remove it from the first step having the option CANCEL without the <

**Comment by zawadz88** [comment]
Hi @sdejesusF,
This seems related to #54.
Thanks for he feedback - we'll try to add it in the next release!

**Comment by zawadz88** [comment]
Hi @sdejesusF,
This was added in v2.3.0. Please see "Custom navigation buttons" in the sample app.

**Comment by sdejesusF** [comment]
Hi @zawadz88 
Great! thank you so much I will try it.
