### ISSUE TITLE
Failed to find style 'ms_stepperStyle' in current theme

### ISSUE THREAD

**Issue by poltographer6** [stepstone-tech/android-material-stepper#60]
How to fix this? I'm just starting using this stepper. When I add this code:

<?xml version="1.0" encoding="utf-8"?>
<com.stepstone.stepper.StepperLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/stepperLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    app:ms_stepperType="progress_bar" />

on my layout that error shows.

**Comment by zawadz88** [comment]
Hi,
Thanks for the report!
Is it an error that shows in Preview in Android Studio or is it crash that happens when you run the app?

**Comment by poltographer6** [comment]
Hello! It shows in preview. I'm not yet trying to run the app. Is it normal?

**Comment by zawadz88** [comment]
Hi @poltographer6,
This should be fixed in 2.3.1. Please check if it's working now. You might need to rebuild the project in Android Studio first.

Again, thanks for the bug report!

**Comment by poltographer6** [comment]
Rendering Problems:

NOTE: One or more layouts are missing the layout_width or layout_height attributes. These are required in most layouts.

Is this normal? I'm so sorry I really don't have an idea with libraries. I'm just a beginner in Android development.

**Comment by zawadz88** [comment]
What Android Studio version are you using?
Also could you share the screenshot containing your layout XML and the Preview?

**Comment by poltographer6** [comment]
I'm using Android Studio 2.2.3
![pic](https://cloud.githubusercontent.com/assets/26056672/23402229/a545b2fa-fde5-11e6-87c8-8532319f1e02.PNG)

**Comment by zawadz88** [comment]
@poltographer6,
Thanks for the feedback! 
This works fine for some reason in the layouts from the sample app, but does not when the library is included as an AAR. I'll investigate further.

**Comment by zawadz88** [comment]
@poltographer6 This should be fixed now with 2.3.2.

**Comment by poltographer6** [comment]
@zawadz88  No more errors! Thank you so much! :)
