### ISSUE TITLE
Can't access fragment instances in adapter

### ISSUE THREAD

**Issue by seasox** [stepstone-tech/android-material-stepper#64]
AbstractFragmentStepAdapter.findStep(ViewPager, int) requires ViewPager as first attribute and uses its getId(), which, as I see it it, always resolves to R.id.ms_stepPager. Would it be possible to remove ViewPager from findStep or provide an overloaded findStep(int)?

My actual issue is that AbstractFragmentStepAdapter.getItem() calls createStep() internally, so I cannot access the actual fragment instances in my adapter, since they are recreated in createStep(). I also can't use findStep, since I cannot get the ViewPager from StepperLayout.

A getter for StepperLayout.mPager would do the job, too.

Another solution to this issue might be to change the implementation of AbstractFragmentStepAdapter.getItem(int) to check findStep() != null before calling createStep

I could file a PR if you agree.

//edit:
I can access the fragments using FragmentManager (as proposed in #39), but this still involves R.id.ms_stepPager. Accessing the fragments using their adapter would be cleaner, IMHO.

**Comment by seasox** [comment]
Another solution to this issue might be to change the implementation of AbstractFragmentStepAdapter.getItem(int) to check findStep() != null before calling createStep

**Comment by zawadz88** [comment]
Hi @seasox,
Thanks for the feedback!

I agree with the proposed solution:
> AbstractFragmentStepAdapter.findStep(ViewPager, int) requires ViewPager as first attribute and uses its getId(), which, as I see it it, always resolves to R.id.ms_stepPager. Would it be possible to remove ViewPager from findStep or provide an overloaded findStep(int)?

You are right - the ViewPager argument is redundant since this is always used with the ViewPager with R.id.ms_stepPager therefore it can be removed.

**Comment by zawadz88** [comment]
Please see the changes in #65. Will that work for you?

**Comment by seasox** [comment]
Hi @zawadz88, thank you! This should work.

**Comment by zawadz88** [comment]
Ok, this is now merged to _master_ and will be in the next release. Thanks for the feedback!
