### ISSUE TITLE
I need help for creating my new signup activity

### ISSUE THREAD

**Issue by poltographer6** [stepstone-tech/android-material-stepper#67]
How can I create stepper activity with 3 fragments? Do I have to create 3 classes for each step? Or just 3 xml layout?

**Comment by zawadz88** [comment]
You can create 1 class for the fragment and use different layouts depending on the step or create 3 separate classes. It's up to you.
See: 
https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/step/fragment/StepFragmentSample.java
https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/adapter/SampleFragmentStepAdapter.java
