### ISSUE TITLE
Setting error state programmatically

### ISSUE THREAD

**Issue by arslancharyev31** [stepstone-tech/android-material-stepper#68]
Good day! Thanks for implementing 'error state' feature, works great. But I couldn't find a way to set the error state programmatically. Is it supported by the library?

**Comment by zawadz88** [comment]
Hi @arslancharyev31,
This is currently not possible. Internally we set the error via calls like `mStepperType.setErrorStep(mCurrentStepPosition, false)` in `StepperLayout`.

Could you explain your use case in which you would like to set it programmatically?

**Comment by arslancharyev31** [comment]
I have a login screen. When user clicks next, dialog opens and network is done. If credentials are valid, then goes to next step, otherwise stays.

**Comment by leonardo2204** [comment]
@zawadz88 If you'd like I can drop a PR on that !

**Comment by zawadz88** [comment]
Hi,
@leonardo2204 thanks but already done :) Merged in #71
