### ISSUE TITLE
Feature request: Error state annimation

### ISSUE THREAD

**Issue by arslancharyev31** [stepstone-tech/android-material-stepper#69]
Good day! I think it would be nice if error state triangle would wobble a bit horizontally for a sec (just like the button in the sample app) when error state just occurs. Also would be nice to enable/disable this option via both xml and java.

**Comment by zawadz88** [comment]
Hi @arslancharyev31,
That sounds like a nice enhancement! 
I'm wondering about the default animation to use though as I'm not sure about Material guidelines for displaying errors with animations. The official documentation doesn't specify this: https://material.io/guidelines/components/steppers.html#steppers-types-of-steppers :/

**Comment by arslancharyev31** [comment]
I think the animation like the one of shaking button in the sample app would look appropriate. Support for custom anim would also seem feasable, in case someone is not satisfied with default one.

**Comment by zawadz88** [comment]
This feature is partially done on `feature/issue-69` branch, however after looking at the final animation it feels a bit odd. I think a more Material animation should take place instead, e.g. the circle with step number should morph into the warning icon (possibly by using an animated vector drawable). This will be more time consuming though...

**Comment by arslancharyev31** [comment]
Morphing sounds cool. Is it going to be something like [this](https://www.youtube.com/watch?v=ONly8BZbbiI)?

**Comment by zawadz88** [comment]
It's something I had in mind :)

**Comment by arslancharyev31** [comment]
What about the number in the center of the circle? I have some trouble imagining morphing of a number into triangle :P

**Comment by zawadz88** [comment]
Released in 3.0.0
