### ISSUE TITLE
Setting StepTabsContainer background via attribute.

### ISSUE THREAD

**Issue by arslancharyev31** [stepstone-tech/android-material-stepper#72]
Good day. There is a nice attribute `ms_bottomNavigationBackground` in StepperLayout to change bottom navigation background. But I couldn't find similar attribute for StepTabs. Instead we need to  define a style for `ms_tabsContainerStyle` with `android:background` in it and assign it to `ms_stepperLayoutTheme`. It would be nice to be able to have a simple attribute instead of defing numerous styles just for that. Thank you!

**Comment by zawadz88** [comment]
Hi @arslancharyev31 ,
I have mixed feelings about this TBH. The idea of introducing `ms_stepperLayoutTheme` was to actually limit the number of StepperLayout's custom attributes (which is already at 19).
The way I see it If I wanted to e.g. change the default background I would also add some elevation to the view and modify it further (so modify `android:background` and `android:elevation` on Lollipop). We could introduce custom attributes for each of the views inside of the Stepper layout (which is a few), but I feel like it would be harder to find the right attribute.

PS.
`ms_bottomNavigationBackground` was actually introduced before `ms_stepperLayoutTheme` and if I were to do it again I would probably skip `ms_bottomNavigationBackground`.

**Comment by arslancharyev31** [comment]
Definitely writing attribute for every single view would be not a good practice. But for major views like bottom bar and step tabs it shouldn't be a big deal, imho. Thanks anyway!
