### ISSUE TITLE
Option to disable navigation via tabs

### ISSUE THREAD

**Issue by arslancharyev31** [stepstone-tech/android-material-stepper#73]
Good day. I couldn't find a way to disable navigation via step tabs. I think an option to enable/disable this via both xml and java would seem reasonable.

**Comment by zawadz88** [comment]
Hi @arslancharyev31,
So you would like to be able to navigate only by using the bottom navigation?
I'm wondering if this behaviour is not against the guidelines? In what scenario would you like to disable this?

**Comment by arslancharyev31** [comment]
A login step, followed by customization step. It just doesn't seem right for me to click on 'Customize' tab (instead of "Sign In" next button) in login step and it will proceed. I think adding this as optional won't violate guidelines.

**Comment by zawadz88** [comment]
Thanks for the feedback!
I'd say you're right - it does seem a bit off.
This should be a relatively small change to make.

**Comment by zawadz88** [comment]
Released in 3.0.0
