### ISSUE TITLE
onActivityResult Not being called

### ISSUE THREAD

**Issue by JavoByte** [stepstone-tech/android-material-stepper#74]
HI.

I'm trying to perform some actions after calling an activity in one of my fragments. However, the method `onActivityResult` is being called in the `Activity` but not in the active `Fragment`.

I'm calling `super.onActivityResult` on my `Activity` so that's not the problem.

What can be happening?

**Comment by zawadz88** [comment]
Hi,
Are you calling startActivityForResult on the Fragment or on the Acrivity?
The library does not really do anything here to mess the default behaviour of Fragments used in a ViewPager.

**Comment by JavoByte** [comment]
I'm calling it on the Fragment, but it doesn't get called. To test, I
called it in the Activity. It actually gets called in the Activity but not
in the Fragment. I did a little research about the subject and it usually
happens if the fragmen is a child of another Fragment. I checked out your
code and this doesn't seem to be the case. But better asking. Does your
package shows my fragments inside other Fragment?

**Comment by zawadz88** [comment]
No, the step Fragments are simply put in a ViewPager so no magic there... Is the same happening if you put the Fragments in a ViewPager?
I cannot really think of any reason the library itself would be messing this up TBH.

**Comment by JavoByte** [comment]
Found my problem. I'm actually calling `startActivityForResult` from a
custom View. So, the real problem is that, there, I'm using `getContext`
which is the Activity. Not the fragment. I should call it from the
fragment. Is there anyway to get the current fragment tag? So I can find if
with the fragment manager?

**Comment by zawadz88** [comment]
It depends where you current view is really. There will be a method added in next release to get the step from adapter: https://github.com/stepstone-tech/android-material-stepper/issues/64
however I cannot really give any timeline on that currently.
For the time being I guess you could get the fragment as in findStep(..) in AbstractFragmentStepAdapter.java
