### ISSUE TITLE
Stop Next button on going up

### ISSUE THREAD

**Issue by poltographer6** [stepstone-tech/android-material-stepper#75]
How can I stop the next button on going up when the keyboard shows?

![screenshot_1488588014](https://cloud.githubusercontent.com/assets/26056672/23574127/4fd6af4e-00b6-11e7-994f-ac2242b6d889.png)
![screenshot_1488588018](https://cloud.githubusercontent.com/assets/26056672/23574126/4fd42f62-00b6-11e7-911c-50f00d98cdb5.png)

**Comment by zawadz88** [comment]
Hi @poltographer6,
Please see https://developer.android.com/guide/topics/manifest/activity-element.html#wsoft

**Comment by poltographer6** [comment]
@zawadz88  Thanks so much! One more question, where should I place those error traps for my edittexts? Should I place them in verifyStep()?

**Comment by zawadz88** [comment]
Glad it helped :)
Yes, please see https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/step/fragment/FormStepFragment.java

**Comment by poltographer6** [comment]
Hello @zawadz88 !

Just a question, how can I implement this to verifyStep()?

` // error trapping for AppName
    class VerifyAppNameTask extends AsyncTask<String, Void, String> {
        // use doInBackground() to make network calls, the returned value is
        // sent to onPostExecute()
        @Override
        protected String doInBackground(String... data) {

            if (sAppName.replace(" ","").isEmpty())
            {
                return "1";
            }
            else if (sAppName.length() > 25)
            {
                return "2";
            }
            else if (checkAppName(data[0]))
            {
                return "3";
            }
            else
            {
                return "4";
            }


        }
        @Override
        protected void onPostExecute(String result) {
            tilAppName.setErrorEnabled(true);
            switch(result)
            {
                case "1":   {tilAppName.setError("You can't leave this empty.");break;}
                case "2":   {tilAppName.setError("Maximum of 25 characters.");break;}
                case "3":   {tilAppName.setError("No spaces allowed");break;}
                case "4":   {tilAppName.setError(null);tilAppName.setErrorEnabled(false);break;}

            }

        }
    }`

**Comment by poltographer6** [comment]
Another thing is that I have more than 1 edittext inside a step. So for example I have
VerifyAppVerisionTask
VerifyAppDescriptionTask
VerifyAppPlatformTask

how can i insert them in Verification method?
