### ISSUE TITLE
Question about Verifying

### ISSUE THREAD

**Issue by poltographer6** [stepstone-tech/android-material-stepper#77]
Can anybody help me with this?
How can I verify edittexts inside my Step?

I have diferrent verification methods for each edittext
`Hello @zawadz88 !

Just a question, how can I implement this to verifyStep()?

`

    class VerifyAppNameTask extends AsyncTask<String, Void, String> {
        // use doInBackground() to make network calls, the returned value is
        // sent to onPostExecute()
        @Override
        protected String doInBackground(String... data) {

            if (sAppName.replace(" ","").isEmpty())
            {
                return "1";
            }
            else if (sAppName.length() > 25)
            {
                return "2";
            }
            else if (checkAppName(data[0]))
            {
                return "3";
            }
            else
            {
                return "4";
            }

        }
        @Override
        protected void onPostExecute(String result) {
            tilAppName.setErrorEnabled(true);
            switch(result)
            {
                case "1":   {tilAppName.setError("You can't leave this empty.");break;}
                case "2":   {tilAppName.setError("Maximum of 25 characters.");break;}
                case "3":   {tilAppName.setError("No spaces allowed");break;}
                case "4":   {tilAppName.setError(null);tilAppName.setErrorEnabled(false);break;}

            }

        }
    }`

above code is one of my error traps

My problem is how can I verify edittexts then when there's no more error, Next > button will enable again. Thank you so much for you help!

**Comment by zawadz88** [comment]
Hi @poltographer6,
I don't really understand your question:

> My problem is how can I verify edittexts then when there's no more error, Next > button will enable again.

Could explain with an example from user's perspective?

**Comment by poltographer6** [comment]
Alright.  Here is my Step 1 Fragment:
![4fd6af4e-00b6-11e7-994f-ac2242b6d889](https://cloud.githubusercontent.com/assets/26056672/23647707/2d2781dc-0352-11e7-8f4b-df9ff6872ea1.png)

As you can see I have 5 Edittexts there. Each of them has own created method for data verification
Example of the verification for the Application Name is:

` class VerifyAppNameTask extends AsyncTask<String, Void, String> {
        // use doInBackground() to make network calls, the returned value is
        // sent to onPostExecute()
        @Override
        protected String doInBackground(String... data) {

            if (data[0].replace(" ","").isEmpty())
            {
                f1 = true;
                return "1";
            }
            else if (data[0].length() > 25)
            {
                f1 = true;
                return "2";
            }
            else if (checkAppName(data[0]))
            {
                f1 = true;
                return "3";
            }
            else
            {
                f1 = false;
                return "4";
            }


        }
        @Override
        protected void onPostExecute(String result) {
            tilAppName.setErrorEnabled(true);
            switch(result)
            {
                case "1":   {tilAppName.setError("You can't leave this empty.");break;}
                case "2":   {tilAppName.setError("Maximum of 25 characters.");break;}
                case "3":   {tilAppName.setError("No spaces allowed");break;}
                case "4":   {tilAppName.setError(null);tilAppName.setErrorEnabled(false);break;}

            }

        }
    }
`

I used Asynctask for the App name verification.

And for the AppCategory EditText here is my verification method

` public boolean edtAppCategoryET(String data)
    {

        tilAppCategory.setErrorEnabled(true);
        if (data.replace(" ","").equals(""))
        {
            tilAppCategory.setError("You can't leave this empty.");
            return true;
        }
        else
        {
            tilAppCategory.setError("");
            tilAppCategory.setErrorEnabled(false);
            return false;
        }
    }`

Same goes with the other EditTexts. 
They have also a OnFocusChangeListener. 
My problem is I don't know how will I implement these methods to Stepper. When there's no error in any EditTexts, the Next button will enable. I'm having a hard time understanding the library because im a beginner in android app development.

**Comment by zawadz88** [comment]
OK,
Basically it's your decision when do you want to do your verification - the library does not impose when you have to do it.

So you could verify these inputs e.g. as the user types and change the state of the Next button as in the sample app (see https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/AbstractStepperActivity.java and https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/step/fragment/StepFragmentSample.java).

You could also verify the entire step in `verifyStep()` and e.g. make the API calls for all the forms in one go. It's up to you really.

**Comment by poltographer6** [comment]
Im still confused. Where should I put these method:
edtAppCategoryET()
edtAppVersionET()
edtAppPlatform()

^
inside those are my error trapping.. And on my previous activity on my app. they return boolean to check if there are errors or none, if none, then it will proceed to another activity. How can i implement this on Step?

**Comment by poltographer6** [comment]
Hello @zawadz88 ! Forget my above question, I just want to ask if the Next button can act like a Button? Like I can do this thing: nextbutton.setEnabled(true); something like that?

**Comment by zawadz88** [comment]
Hi @poltographer6,
Yes it can. setEnabled() is a method that's available on the View class BTW. Something similar is happening in the sample app. Please see e.g. "STYLED DOTS" in the samples.

**Comment by poltographer6** [comment]
Hello @zawadz88  sorry for so many questions, but I can't find how to can I do that .setEnabled on the stepperlayout's Next Button.

**Comment by poltographer6** [comment]
Hi @zawadz88  so sorry for disturbing you but I already fixed my problems. :) Thanks!

**Comment by vijaya842** [comment]
hi @poltographer6 I am struggling at this validation. can you please tell me how to validate the edittexts in step.

**Comment by vijaya842** [comment]
please anyone help me
