### ISSUE TITLE
When I rotate the screen, the stepper will go back to step 1

### ISSUE THREAD

**Issue by poltographer6** [stepstone-tech/android-material-stepper#80]
Why is it happening?

**Comment by zawadz88** [comment]
Hi,
The StepperLayout does not save the position by itself. It is however possible to initialize it with a previously saved position.
Please see https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/AbstractStepperActivity.java for an example of how to do that.
