### ISSUE TITLE
How to collect data from steps?

### ISSUE THREAD

**Issue by utkarshdalal** [stepstone-tech/android-material-stepper#81]
Hi - I have a newbie question, but this wasn't clear to me from the other questions or from the examples.
I have a stepper with three steps. Whenever I press the next button, I want to save information from the current step and move on to the next one. At the end, when I press complete, I want to consolidate the information from the three steps and make a REST API call. What's the best way to do this?

As an example - in my first step, I want the user to input a location. In the second, I want the user to choose a category. In the third, I want the user to provide a description. Finally, when the user presses complete, I want to make a REST call using the location, category and description.

**Comment by zawadz88** [comment]
Hi @utkarshdalal,
I think this is slightly related to this: https://github.com/stepstone-tech/android-material-stepper/issues/15
Please see if this answers your question.

**Comment by utkarshdalal** [comment]
Hi @zawadz88 
Thanks for the response.
That helps, but how do I know when to collect the data? Ideally I would do this when the next button is pressed; is there something like an onNextButtonPressed() method?

**Comment by zawadz88** [comment]
Hi @utkarshdalal,
I think it's up to you. Ideally you could save that data once it actually changes in your step.

> is there something like an onNextButtonPressed() method?
For this you could probably use `BlockingStep#onNextClicked(StepperLayout.OnNextClickedCallback callback)`.

Please let me know if this works for you.

**Comment by utkarshdalal** [comment]
Hey @zawadz88,
I ended up making my fragments implement BlockingStep instead of Step for my fragments, and then storing inputted data in the onNextClicked() method, and then storing the data in an object in my activity.

If I may make a suggestion - I think entering and saving data is quite a common use case for this library, so I think if you added an example of how to do this in the readme it would be really helpful and would probably help increase usage and adoption of it!

Either way, thanks for your help!

**Comment by zawadz88** [comment]
Hi @utkarshdalal,
Thanks for the feedback. I'll update the README once #87 is merged!

**Comment by hardikamal** [comment]
Hi @utkarshdalal could you help me with storing object...?
