### ISSUE TITLE
Incompatibility with material-spinner

### ISSUE THREAD

**Issue by thyagoollive** [stepstone-tech/android-material-stepper#82]
Both components contain attribute named ms_errorColor with different formats (types).
Therefore, it is impossible to use the 2 components at the same time.
Do you have any solution?

![ms_errorcolor attribute](https://cloud.githubusercontent.com/assets/9834310/23762689/8f0573f8-04d5-11e7-8d38-01129e322fb9.jpg)

**Comment by zawadz88** [comment]
Hi,
I guess the best you could is to edit the code of either this library or material-spinner and change the attribute name to sth different and include that edited library either as a separate Gradle module or as an AAR in your project :/

I guess there's too many Material libraries available hence the naming clash :)
