### ISSUE TITLE
Step color

### ISSUE THREAD

**Issue by khrystynapochynok** [stepstone-tech/android-material-stepper#84]
Hello,

Is it possible to set color for each step by index, not just for active and inactive steps in general?

**Comment by zawadz88** [comment]
Hi,
It is not possible currently. 
Could you explain why would you like to do that and for which stepper type (dots, progress bar or tabs)?

**Comment by khrystynapochynok** [comment]
I have some kind of quiz with one question on each step. I need to indicate step with green, red or yellow color depending whether answer was correct, wrong or partially correct. I am using horizontal stepper.

**Comment by zawadz88** [comment]
Thanks for the explanation. As I said, this is currently not possible. 
It's a rather unusual case to be honest and not really mentioned in the Material doc, however I am happy to review any PR regarding this!

**Comment by leonardo2204** [comment]
I don't mean to be rude, but that doesn't feel like the main point of the lib, which is "being materialistic", by the guidelines. IMO, this feels like a custom use case, where forking would do.

**Comment by khrystynapochynok** [comment]
Sure, thanks for the answer.
