### ISSUE TITLE
How to get values from Edittexts on my Steps?

### ISSUE THREAD

**Issue by poltographer6** [stepstone-tech/android-material-stepper#85]
I need all the values from step 1-4 to insert into my database. Now my problem is, where should I do the process? On onCompleteted() in my MainActivity? Now my question is, how can I get the values I entered on the steps? BTW, i used this method in creating steps on my AbstractFragmentStepAdapter

` public Step createStep(@IntRange(from = 0L) int position) {
        switch (position) {
            case 0:
                return AppUploadStep1.newInstance(R.layout.content_app_upload_step1);
            case 1:
                return AppUploadStep2.newInstance(R.layout.content_app_upload_step2);
            case 2:
                return AppUploadStep3.newInstance(R.layout.content_app_upload_step3);
            case 3:
                return AppUploadStep4.newInstance(R.layout.content_app_upload_step4);
            default:
                throw new IllegalArgumentException("Unsupported position: " + position);
        }
    }`

**Comment by gigiperih** [comment]
@poltographer6 how to solve this issue mate?
