### ISSUE TITLE
Help me about onComplete()

### ISSUE THREAD

**Issue by poltographer6** [stepstone-tech/android-material-stepper#86]
Okay, I have BlockingSteps, at the last step, the Next Button was changed to Complete, the problem is, the process inside onComplete() is not displaying (ex. Toast). Can somebody help me with this?

**Comment by FWStelian** [comment]
@poltographer6  what are you doing in `verifyStep()` in your Fragment ? If you want the button to be disabled until the user selects a file ( verifyStep will return an error if there is no file selected) you need to manually call `verifyStep()` when the file is available.

**Comment by poltographer6** [comment]
I didn't edit verifyStep().. Next button is always enabled. It works fine until the last step, Complete button doesnt do anything.  I used BlockingStep so that I can use method onNextClicked(). In that method I check for errors. If there's no error, it will call  callback.goToNextStep(); The only problem is the Complete button, It's like there's no listener for that button.

**Comment by FWStelian** [comment]
@poltographer6   as discussed in #52  and #83  the last fragment will not call `onNextClicked()`.

So you can either wait for #87  to be approved or find some workaround (#52 mentions some).

You can also look in the sample app and see how `OnProcessListener` is used.

Another thing, in the source code you provided in #83  I noticed that you didn't set the listener to the stepper layout  (you are missing  `mStepperLayout.setListener(this);`).

**Comment by poltographer6** [comment]
Thanks for this!
mStepperLayout.setListener(this)

**Comment by poltographer6** [comment]
But I think we need the request to check if there's no error in the last step before proceeding to onComplete()
