### ISSUE TITLE
Views in fragment are selectable while Stepper Feedback progress is shown

### ISSUE THREAD

**Issue by arslancharyev31** [stepstone-tech/android-material-stepper#93]
Good day. Thanks for the stepper feedback feature, looks awesome. However, it doesn't make views inside of a fragment unclickable or unselectable while feedback progess is shown. For instance I can edit my text fields while progress is shown, which is undesirable behaviour. It would be nice if the library would do that automaticaly, instead of doing that manually for each fragment or view. Thank you.

P.S.: I think it should be written in wiki that in order to have disabled effect on bottom navigation bar, button colors should be assigned using selectors like in sample app:
`   app:ms_backButtonColor="@color/ms_disabling_button_text_color_selector"
    app:ms_nextButtonColor="@color/ms_disabling_button_text_color_selector"
    app:ms_completeButtonColor="@color/ms_disabling_button_text_color_selector"`
Because it took me quite a while to figure out why my navigation bar buttons aren't changing their color.

**Comment by zawadz88** [comment]
Hi,
I agree about the readme description, I'll update it so there's no confusion there :)

However, as far as the view selection is concerned i think this shouldn't be done by the library. You mentioned EditText, however this can be any other view (including custom views)  and there's no way for the library to know how to disable it, e.g. it could be simply calling setEnabled(false), but it doesn't have to. It could also mean stopping some ongoing animations, etc. Therefore, I believe this should be the Step's responsibility to do that.

**Comment by arslancharyev31** [comment]
I think simply infalting an empty view which would overlay and dim the content and at the same time intercept all clicks, so that they don't reach underlying content. It would also fix another issue of mine, where content behind stepper layout is not being dimmed.

**Comment by zawadz88** [comment]
I tried putting a view to dim the content, however I found that the effect was worse than changing alpha since it could look completely different depending on what's inside the step (especially with different step backgrounds).
However if you have any ideas how to make this better I'll gladly accept PRs regarding this!

**Comment by arslancharyev31** [comment]
How about for time adding an option to choose the dim type? Alpha by default but optional overlay. Also would be nice to be able to change alpha amount and overlay color.

Here's how my implementation looks like, to make it clear.
### Expected behavior
![expected](https://cloud.githubusercontent.com/assets/20893266/24076373/ae9c7646-0c3f-11e7-9357-b2974223c72c.png)
### Real behaviour
![real](https://cloud.githubusercontent.com/assets/20893266/24076376/bcedf760-0c3f-11e7-8a74-dfed1969977e.png)
### Even worse with keyboard :)
![real_kb](https://cloud.githubusercontent.com/assets/20893266/24076372/ae9c2e34-0c3f-11e7-8f5c-6d7d904019b2.png)

**Comment by zawadz88** [comment]
I'd suggest splitting `content` feedback type into `content_dim`, `content_fade` stepper feedback types then? Also, new attributes `ms_stepperFeedback_contentDimBackground` and `ms_stepperFeedback_contentFadeAlpha` could be added for further customisation?

**Comment by arslancharyev31** [comment]
Exactly. This offers good flexibility for developers.

**Comment by zawadz88** [comment]
I think that click intercepting could be also done for `content_fade ` or we could create e.g. `disabled_content_interactions` feedback type.

**Comment by arslancharyev31** [comment]
`disabled_content_interactions` feedback type sounds excellent. I'm looking forward to see these features in future releases!

**Comment by zawadz88** [comment]
This was merged to develop and will be available with the next release. 
Thanks for contributing!
