### ISSUE TITLE
Disabling only one of the navigation buttons when stepper feedback is shown

### ISSUE THREAD

**Issue by arslancharyev31** [stepstone-tech/android-material-stepper#94]
Good day. I was implementing request cancelling while stepper feedback is shown and faced following dilema: if I set to disable nav bar buttons I can't click the back button (which is titled "Cancell") as well as hardware back button. At the same time if I choose not to disable nav bar buttons I can click on the next button(which is titled "Sign In") which doesn't make sense so I would preffer it to be disabled. So my question is: Is there a way to disable only next button but keep navigation back button along with hardware back buton enabled?

**Comment by zawadz88** [comment]
Hi @arslancharyev31,
You could do that by omitting the `disabled_bottom_navigation` flag and calling `StepperLayout#setNextButtonEnabled(enabled)` instead when you call  `StepperLayout#showProgress(progressMessage)`/`StepperLayout#hideProgress()`

**Comment by arslancharyev31** [comment]
Thanks, that's exactly what I wanted.
