### ISSUE TITLE
implement onBackClicked in menuItem Home (back arrow in ActionBar)

### ISSUE THREAD

**Issue by Abdurrahmanjun** [stepstone-tech/android-material-stepper#95]
good day sir. thank you for this, it an awesome stepper.. any idea how implement onBackClicked from fragment to menuItem Home which it generated in the activity and make the activity finish() while it at step 0 ??

**Comment by zawadz88** [comment]
Hi @Abdurrahmanjun,
You can see an example of how to handle back clicks in the sample app, e.g. https://github.com/stepstone-tech/android-material-stepper/blob/master/sample/src/main/java/com/stepstone/stepper/sample/AbstractStepperActivity.java

**Comment by Abdurrahmanjun** [comment]
i see.. i used that project for my reference, but i missed that procedure. thank you @zawadz88 hope  good thing in life comeback to you. cheers!
