### ISSUE TITLE
passing some data 

### ISSUE THREAD

**Issue by tank777** [stepstone-tech/android-material-stepper#96]
how to pass the data from one step to next step?

**Comment by zawadz88** [comment]
Hi @tank777,
Please see #15 and #81

**Comment by tank777** [comment]
any example?

**Comment by arslancharyev31** [comment]
I think writing a section about that in Readme would prevent devs asking the same question over and over again.

**Comment by zawadz88** [comment]
@tank777 @arslancharyev31 I've added a sample in #98. Please let me know if this is sufficient in your opinion.

**Comment by tank777** [comment]
thank you

**Comment by zawadz88** [comment]
The sample is now available on the master branch.
