### ISSUE TITLE
make the bottomnavigation stay in the bottom

### ISSUE THREAD

**Issue by Abdurrahmanjun** [stepstone-tech/android-material-stepper#99]
good day, am i missed another thing? when i use the edittext inside my form (whichis there are inside the fragment of this awesome stepper) the bottomnav included right before the keyboard. the problem come when i use android:imeoption:"actionnext" it going to that next onclick button while it should be going to the other edittext tag. any idea how to solve this minor problem? some user just feel uncomfortable with this situation. any leads will so much help, thanks.

**Comment by zawadz88** [comment]
Hi @Abdurrahmanjun,
It probably depends how you handle this in your `OnEditorActionListener` as the library does not really do anything with the key events itself.
What's your code?

**Comment by Abdurrahmanjun** [comment]
ok, i dont think this is an issue.. thanks for the fast respone. cheers
